let tbl = __str_bytes(__file_read("json/udc_p_table.bin"));
fn ms(m) { return __floor(m / 4096) % 16; };
fn mr(m) { return __floor(m / 256) % 16; };
fn mv(m) { return __floor(m / 32) % 8; };
fn ma(m) { return __floor(m / 4) % 8; };
let checkpoint = __heap_save();
let book = __file_read("data/cuon_theo_chieu_gio.txt");
let book_len = __len(book);
emit "=== CUON THEO CHIEU GIO ===";
emit "Bytes:"; emit book_len;
let paragraphs = split(book, "\n\n");
let para_count = __array_len(paragraphs);
emit "Paragraphs:"; emit para_count;
let para_mols = [];
let word_total = 0;
let pi = 0;
while pi < para_count { let para = __array_get(paragraphs, pi); let words = split(para, " "); let wc = __array_len(words); let pmol = 0; let wi = 0; while wi < wc { let word = __array_get(words, wi); let wlen = __len(word); if wlen > 0 { let wmol = 0; let ci = 0; while ci < wlen { let cp = __utf8_cp(word, ci); let cl = __utf8_len(word, ci); let off = cp * 2; if off + 1 < 314772 { let lo = __array_get(tbl, off); let hi = __array_get(tbl, off + 1); let m = lo + hi * 256; if m > 0 { if wmol == 0 { let wmol = m; } else { let cs = __floor(wmol / 4096) % 16; let cr = __floor(wmol / 256) % 16; let cv = __floor(wmol / 32) % 8; let ca = __floor(wmol / 4) % 8; let ct = wmol % 4; let ns = __floor(m / 4096) % 16; let nr = __floor(m / 256) % 16; let nv = __floor(m / 32) % 8; let na = __floor(m / 4) % 8; let nt = m % 4; let wmol = __floor((cs*2+ns)/3)%16*4096 + __floor((cr*2+nr)/3)%16*256 + __floor((cv*2+nv)/3)%8*32 + __floor((ca*2+na)/3)%8*4 + __floor((ct*2+nt)/3)%4; }; }; }; let ci = ci + cl; }; if wmol > 0 { if pmol == 0 { let pmol = wmol; } else { let cs = __floor(pmol / 4096) % 16; let cr = __floor(pmol / 256) % 16; let cv = __floor(pmol / 32) % 8; let ca = __floor(pmol / 4) % 8; let ct = pmol % 4; let ns = __floor(wmol / 4096) % 16; let nr = __floor(wmol / 256) % 16; let nv = __floor(wmol / 32) % 8; let na = __floor(wmol / 4) % 8; let nt = wmol % 4; let pmol = __floor((cs*2+ns)/3)%16*4096 + __floor((cr*2+nr)/3)%16*256 + __floor((cv*2+nv)/3)%8*32 + __floor((ca*2+na)/3)%8*4 + __floor((ct*2+nt)/3)%4; }; let word_total = word_total + 1; }; }; let wi = wi + 1; }; if pmol > 0 { __push(para_mols, pmol); }; let pi = pi + 1; };
__heap_restore(checkpoint);
let encoded_paras = __array_len(para_mols);
emit "Words:"; emit word_total;
emit "Encoded paragraphs:"; emit encoded_paras;
emit "--- First 5 paragraph fingerprints ---";
let si = 0;
while si < 5 { if si < encoded_paras { emit __array_get(para_mols, si); }; let si = si + 1; };
emit "--- Book fingerprint (compose all paras) ---";
let book_mol = 0;
let bi = 0;
while bi < encoded_paras { let pm = __array_get(para_mols, bi); if book_mol == 0 { let book_mol = pm; } else { let cs = __floor(book_mol / 4096) % 16; let cr = __floor(book_mol / 256) % 16; let cv = __floor(book_mol / 32) % 8; let ca = __floor(book_mol / 4) % 8; let ct = book_mol % 4; let ns = __floor(pm / 4096) % 16; let nr = __floor(pm / 256) % 16; let nv = __floor(pm / 32) % 8; let na = __floor(pm / 4) % 8; let nt = pm % 4; let book_mol = __floor((cs*2+ns)/3)%16*4096 + __floor((cr*2+nr)/3)%16*256 + __floor((cv*2+nv)/3)%8*32 + __floor((ca*2+na)/3)%8*4 + __floor((ct*2+nt)/3)%4; }; let bi = bi + 1; };
emit "Fingerprint:"; emit book_mol;
emit "S:"; emit ms(book_mol); emit "R:"; emit mr(book_mol); emit "V:"; emit mv(book_mol); emit "A:"; emit ma(book_mol);
emit "=== 3.2MB -> paragraph mols -> 1 book mol ===";
emit "PASS";
