let ok = 1;
let tbl = __str_bytes(__file_read("json/udc_p_table.bin"));
fn pw(cp) { let off = cp * 2; let lo = __array_get(tbl, off); let hi = __array_get(tbl, off + 1); return lo + hi * 256; };
fn ms(m) { return __floor(m / 4096) % 16; };
fn mr(m) { return __floor(m / 256) % 16; };
fn mv(m) { return __floor(m / 32) % 8; };
fn ma(m) { return __floor(m / 4) % 8; };
fn mt(m) { return m % 4; };
let pw_a = pw(97);
if pw_a != 2448 { let ok = 0; emit "FAIL a"; emit pw_a; };
let pw_e_vn = pw(7879);
if pw_e_vn != 10687 { let ok = 0; emit "FAIL ệ"; emit pw_e_vn; };
let pw_o_vn = pw(7897);
if pw_o_vn != 10693 { let ok = 0; emit "FAIL ộ"; emit pw_o_vn; };
let pw_d_vn = pw(273);
if pw_d_vn != 28257 { let ok = 0; emit "FAIL đ"; emit pw_d_vn; };
let pw_emoji = pw(128512);
if pw_emoji != 137 { let ok = 0; emit "FAIL emoji"; emit pw_emoji; };
let pw_sad = pw(128546);
if pw_sad != 16842 { let ok = 0; emit "FAIL sad"; emit pw_sad; };
let pw_circle = pw(9679);
if pw_circle != 12313 { let ok = 0; emit "FAIL circle"; emit pw_circle; };
let pw_in = pw(8712);
if pw_in != 62092 { let ok = 0; emit "FAIL in"; emit pw_in; };
if pw_e_vn != pw_o_vn { } else { let ok = 0; emit "FAIL ệ==ộ"; };
if pw_emoji != pw_sad { } else { let ok = 0; emit "FAIL emoji==sad"; };
let s_e = ms(pw_e_vn);
let r_e = mr(pw_e_vn);
let v_e = mv(pw_e_vn);
let a_e = ma(pw_e_vn);
let t_e = mt(pw_e_vn);
if s_e != 2 { let ok = 0; emit "FAIL ệ.S"; };
if r_e != 9 { let ok = 0; emit "FAIL ệ.R"; };
if v_e != 5 { let ok = 0; emit "FAIL ệ.V"; };
if a_e != 7 { let ok = 0; emit "FAIL ệ.A"; };
if t_e != 3 { let ok = 0; emit "FAIL ệ.T"; };
if ok { emit "PASS"; } else { emit "FAIL"; };
