let ok = 1;
let keys = [];
let mols = [];
let texts = [];
__push(keys, "hello");
__push(mols, __mol_pack(1, 0, 5, 3, 0));
__push(texts, "A greeting");
__push(keys, "math");
__push(mols, __mol_pack(0, 1, 4, 1, 2));
__push(texts, "Numbers");
__push(keys, "olang");
__push(mols, __mol_pack(2, 3, 6, 4, 1));
__push(texts, "A language");
if __array_len(keys) != 3 { let ok = 0; emit "FAIL count"; };
if __array_get(keys, 0) != "hello" { let ok = 0; emit "FAIL key0"; };
if __array_get(texts, 2) != "A language" { let ok = 0; emit "FAIL text2"; };
let m0 = __array_get(mols, 0);
if __mol_s(m0) != 1 { let ok = 0; emit "FAIL S"; };
if __mol_v(m0) != 5 { let ok = 0; emit "FAIL V"; };
if ok { emit "PASS"; } else { emit "FAIL"; };
