let ok = 1;
let tbl = __str_bytes(__file_read("json/udc_p_table.bin"));
fn pw(cp) { let off = cp * 2; let lo = __array_get(tbl, off); let hi = __array_get(tbl, off + 1); return lo + hi * 256; };
fn ms(m) { return __floor(m / 4096) % 16; };
fn mr(m) { return __floor(m / 256) % 16; };
fn mv(m) { return __floor(m / 32) % 8; };
fn ma(m) { return __floor(m / 4) % 8; };
fn comp(a, b) { let s = __floor((ms(a)*2 + ms(b)) / 3) % 16; let r = __floor((mr(a)*2 + mr(b)) / 3) % 16; let v = __floor((mv(a)*2 + mv(b)) / 3) % 8; let ar = __floor((ma(a)*2 + ma(b)) / 3) % 8; let t = __floor(((a % 4)*2 + (b % 4)) / 3) % 4; return s*4096 + r*256 + v*32 + ar*4 + t; };
let pw_V = pw(86);
let pw_i = pw(105);
let pw_e_vn = pw(7879);
let pw_t = pw(116);
let pw_e = pw(101);
let m1 = comp(pw_V, pw_i);
let m2 = comp(m1, pw_e_vn);
let m_viet = comp(m2, pw_t);
let n1 = comp(pw_V, pw_i);
let n2 = comp(n1, pw_e);
let m_viet2 = comp(n2, pw_t);
if m_viet == m_viet2 { let ok = 0; emit "FAIL Việt==Viet"; };
if m_viet == 0 { let ok = 0; emit "FAIL Việt is 0"; };
let pw_v = pw(118);
let pw_u = pw(117);
let m_vui = comp(comp(pw_v, pw_u), pw_i);
let pw_b = pw(98);
let pw_u2 = pw(117);
let pw_o_vn = pw(7891);
let pw_n = pw(110);
let m_buon = comp(comp(comp(pw_b, pw_u2), pw_o_vn), pw_n);
if m_vui == m_buon { let ok = 0; emit "FAIL vui==buồn"; };
fn dist(a, b) { let ds = (ms(a) - ms(b)) / 15; let dr = (mr(a) - mr(b)) / 15; let dv = (mv(a) - mv(b)) / 7; let da = (ma(a) - ma(b)) / 7; return ds*ds + dr*dr + dv*dv + da*da; };
let d = dist(m_vui, m_buon);
if d == 0 { let ok = 0; emit "FAIL dist is 0"; };
if ok { emit "PASS"; } else { emit "FAIL"; };
