let pass = 1;
let err = [];
let br0_keys = [];
let br0_mols = [];
let br0_subs = [];
let br1_keys = [];
let br1_mols = [];
let br1_subs = [];
let br2_keys = [];
let br2_mols = [];
let br2_subs = [];
let br3_keys = [];
let br3_mols = [];
let br3_subs = [];
let br4_keys = [];
let br4_mols = [];
let br4_subs = [];
let br_names = [];
__push(br_names, "Quy luat Goc");
__push(br_names, "Co May Con Nguoi");
__push(br_names, "Song Chung");
__push(br_names, "Cong Cu & Sang Tao");
__push(br_names, "Cau Hoi Lon");
__push(br0_keys, "pi");
__push(br0_mols, __mol_pack(0, 1, 4, 2, 0));
__push(br0_subs, 0);
__push(br0_keys, "euler");
__push(br0_mols, __mol_pack(0, 1, 4, 2, 0));
__push(br0_subs, 0);
__push(br0_keys, "gravity");
__push(br0_mols, __mol_pack(1, 5, 3, 4, 1));
__push(br0_subs, 1);
__push(br1_keys, "emotion");
__push(br1_mols, __mol_pack(5, 0, 6, 6, 2));
__push(br1_subs, 1);
__push(br2_keys, "grammar");
__push(br2_mols, __mol_pack(3, 2, 4, 3, 0));
__push(br2_subs, 0);
__push(br3_keys, "ai");
__push(br3_mols, __mol_pack(0, 4, 5, 5, 3));
__push(br3_subs, 0);
__push(br4_keys, "truth");
__push(br4_mols, __mol_pack(0, 2, 7, 4, 0));
__push(br4_subs, 0);
let total = __array_len(br0_keys) + __array_len(br1_keys) + __array_len(br2_keys) + __array_len(br3_keys) + __array_len(br4_keys);
if total == 7 { emit "ok total"; } else { __push(err, "total"); };
if __array_len(br0_keys) == 3 { emit "ok br0"; } else { __push(err, "br0"); };
if __array_len(br1_keys) == 1 { emit "ok br1"; } else { __push(err, "br1"); };
if __array_len(br4_keys) == 1 { emit "ok br4"; } else { __push(err, "br4"); };
if __array_get(br_names, 0) == "Quy luat Goc" { emit "ok name0"; } else { __push(err, "name0"); };
if __array_get(br_names, 4) == "Cau Hoi Lon" { emit "ok name4"; } else { __push(err, "name4"); };
// gravity is at index 2 of br0_keys (verified by construction above)
if __array_get(br0_keys, 2) == "gravity" { emit "ok gravity"; } else { __push(err, "gravity"); };
// br0_subs has [0, 0, 1] → 2 entries with value 0
let count_zero = __array_get(br0_subs, 0) + __array_get(br0_subs, 1);
if count_zero == 0 { emit "ok math"; } else { __push(err, "math"); };
let pi_mol = __array_get(br0_mols, 0);
if __mol_s(pi_mol) == 0 { emit "ok pi_s"; } else { __push(err, "pi_s"); };
if __mol_r(pi_mol) == 1 { emit "ok pi_r"; } else { __push(err, "pi_r"); };
let grav_mol = __array_get(br0_mols, 2);
if __mol_s(grav_mol) == 1 { emit "ok grav_s"; } else { __push(err, "grav_s"); };
if __array_len(err) == 0 { emit "PASS"; } else { emit "FAIL"; };
