let ok = 1;
let PHI = 40503;
let MASK = 65535;
let INV = 30599;
fn fhash(p) { return __bit_and(p * PHI, MASK); };
fn funhash(idx) { return __bit_and(idx * INV, MASK); };
if fhash(0) != 0 { let ok = 0; emit "FAIL h0"; };
if fhash(1) != 40503 { let ok = 0; emit "FAIL h1"; };
let h100 = fhash(100);
if funhash(h100) != 100 { let ok = 0; emit "FAIL inv100"; };
let h42 = fhash(42);
if funhash(h42) != 42 { let ok = 0; emit "FAIL inv42"; };
if funhash(fhash(65535)) != 65535 { let ok = 0; emit "FAIL inv65535"; };
let t = __array_range(65536);
let _ = __set_at(t, fhash(100), "hello");
let _ = __set_at(t, fhash(42), "world");
let _ = __set_at(t, fhash(9999), "test");
if __array_get(t, fhash(100)) != "hello" { let ok = 0; emit "FAIL get100"; };
if __array_get(t, fhash(42)) != "world" { let ok = 0; emit "FAIL get42"; };
if __array_get(t, fhash(9999)) != "test" { let ok = 0; emit "FAIL get9999"; };
if __array_get(t, fhash(0)) != 0 { let ok = 0; emit "FAIL empty"; };
let mol = __mol_pack(5, 3, 4, 2, 1);
let _ = __set_at(t, fhash(mol), "mol_entry");
if __array_get(t, fhash(mol)) != "mol_entry" { let ok = 0; emit "FAIL mol"; };
if ok { emit "PASS"; } else { emit "FAIL"; };
