//! # knowtree — Hierarchical KnowTree + Legacy wrappers
//!
//! ## KnowTree (hierarchical, T14)
//!
//! ```text
//! L0 (groups)  → 4 entries   (SDF, MATH, EMOTICON, MUSICAL)
//! L1 (blocks)  → ~59 entries (Unicode blocks)
//! L3 (leaves)  → ~8,846 entries (same order as UCD_TABLE)
//! Topology: L0→L1→L3 via Range indices
//! ~18 KB RAM total
//! ```
//!
//! ## Legacy types (sẽ bị xóa ở T10)
//!
//! - `KnowTreeLegacy` — old TieredStore wrapper
//! - `SlimKnowTreeLegacy` — old SlimNode/SlimPage wrapper

extern crate alloc;
use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;

use alloc::collections::BTreeMap;

use crate::compact::{CompactEdge, CompactNode, NodeWithEdges, SlimNode, SlimPage, TieredStore};
use crate::hash::fnv1a_str;
use crate::molecular::{MolecularChain, Molecule, RelationBase};

// ─────────────────────────────────────────────────────────────────────────────
// KnowTree — hierarchical L0→L1→L3 tree (T14)
// ─────────────────────────────────────────────────────────────────────────────

use core::ops::Range;

/// KnowTree — hierarchical tree mapping L0 (groups) → L1 (blocks) → L3 (leaves).
///
/// ```text
/// L0: group P_weights      (4 entries, ~8B)
/// L1: block P_weights      (~59 entries, ~118B)
/// L3: leaf P_weights       (~8,846 entries, ~17.7KB)
/// Topology: l0_to_l1 + l1_to_l3 ranges (~500B)
/// Total: ~18 KB
/// ```
///
/// Leaf P_weights are in the same order as UCD_TABLE entries,
/// grouped by block (which are grouped by group).
pub struct KnowTree {
    /// L0: group P_weights (4-5 entries)
    l0: Vec<u16>,
    /// L1: block P_weights (~59 entries)
    l1: Vec<u16>,
    /// L3: leaf P_weights (same order as UCD_TABLE)
    l3: Vec<u16>,
    /// Topology: which L1 blocks belong to which L0 group
    l0_to_l1: Vec<Range<u16>>,
    /// Topology: which L3 chars belong to which L1 block
    l1_to_l3: Vec<Range<u16>>,
    /// Number of filled leaf entries
    count: u32,
}

impl KnowTree {
    /// Create empty KnowTree.
    pub fn new() -> Self {
        Self {
            l0: Vec::new(),
            l1: Vec::new(),
            l3: Vec::new(),
            l0_to_l1: Vec::new(),
            l1_to_l3: Vec::new(),
            count: 0,
        }
    }

    /// Bootstrap from UCD crate's generated data.
    ///
    /// Builds the full hierarchy from the static tables generated by ucd/build.rs.
    /// L0 entries are SEALED (never overwritten).
    pub fn bootstrap_from_ucd() -> Self {
        let groups = ucd::groups();
        let blocks = ucd::blocks();
        let table = ucd::table();

        let mut l0 = Vec::with_capacity(groups.len());
        let mut l0_to_l1 = Vec::with_capacity(groups.len());

        // Build L0 (groups) and topology
        let mut l1_cursor: u16 = 0;
        for &(_, pw, block_indices) in groups {
            l0.push(pw);
            let start = l1_cursor;
            l1_cursor += block_indices.len() as u16;
            l0_to_l1.push(start..l1_cursor);
        }

        // Build L1 (blocks) and L1→L3 topology
        let mut l1 = Vec::with_capacity(blocks.len());
        let mut l1_to_l3 = Vec::with_capacity(blocks.len());

        for &(_, pw, chars_start, chars_count) in blocks {
            l1.push(pw);
            l1_to_l3.push(chars_start..(chars_start + chars_count));
        }

        // Build L3 (leaves) — P_weights in same order as UCD_TABLE
        let l3: Vec<u16> = table.iter().map(|e| e.p_weight).collect();
        let count = l3.iter().filter(|&&pw| pw != 0).count() as u32;

        Self {
            l0,
            l1,
            l3,
            l0_to_l1,
            l1_to_l3,
            count,
        }
    }

    /// Lookup P_weight for a codepoint (delegates to ucd::p_weight_of).
    #[inline]
    pub fn get(&self, cp: u32) -> u16 {
        ucd::p_weight_of(cp)
    }

    /// Lookup Molecule for a codepoint.
    #[inline]
    pub fn get_mol(&self, cp: u32) -> Option<Molecule> {
        let pw = self.get(cp);
        if pw != 0 {
            Some(Molecule::from_u16(pw))
        } else {
            None
        }
    }

    /// Check if codepoint has a known P_weight.
    #[inline]
    pub fn contains(&self, cp: u32) -> bool {
        self.get(cp) != 0
    }

    /// Number of filled leaf entries.
    #[inline]
    pub fn count(&self) -> u32 {
        self.count
    }

    /// Number of L0 groups.
    #[inline]
    pub fn group_count(&self) -> usize {
        self.l0.len()
    }

    /// Number of L1 blocks.
    #[inline]
    pub fn block_count(&self) -> usize {
        self.l1.len()
    }

    /// P_weight of a group (L0).
    #[inline]
    pub fn group_p_weight(&self, group_idx: usize) -> u16 {
        self.l0.get(group_idx).copied().unwrap_or(0)
    }

    /// P_weight of a block (L1).
    #[inline]
    pub fn block_p_weight(&self, block_idx: usize) -> u16 {
        self.l1.get(block_idx).copied().unwrap_or(0)
    }

    /// Block indices belonging to a group.
    pub fn group_block_range(&self, group_idx: usize) -> Range<u16> {
        self.l0_to_l1
            .get(group_idx)
            .cloned()
            .unwrap_or(0..0)
    }

    /// Char indices belonging to a block.
    pub fn block_char_range(&self, block_idx: usize) -> Range<u16> {
        self.l1_to_l3
            .get(block_idx)
            .cloned()
            .unwrap_or(0..0)
    }

    /// Sample P_weights by dimension value from L3 (leaf nodes).
    ///
    /// VM.7: Lấy mẫu trực tiếp từ KnowTree thay vì file json ngoài.
    /// Dùng cho formula_adaptive — tính ValenceState/ArousalState từ data thật.
    ///
    /// dim: 0=S, 1=R, 2=V, 3=A, 4=T
    /// value: giá trị dimension cần filter (e.g., V=6)
    /// max_samples: số mẫu tối đa (Fib-sized)
    pub fn sample_by_dim(&self, dim: u8, value: u8, max_samples: usize) -> Vec<u16> {
        let matching: Vec<u16> = self.l3.iter()
            .filter(|&&pw| {
                if pw == 0 { return false; }
                let extracted = match dim {
                    0 => ((pw >> 12) & 0x0F) as u8, // S
                    1 => ((pw >> 8) & 0x0F) as u8,  // R
                    2 => ((pw >> 5) & 0x07) as u8,   // V
                    3 => ((pw >> 2) & 0x07) as u8,   // A
                    4 => (pw & 0x03) as u8,           // T
                    _ => return false,
                };
                extracted == value
            })
            .copied()
            .collect();

        let k = max_samples.min(matching.len());
        matching[..k].to_vec()
    }

    /// Get all L3 P_weights (for formula_adaptive fallback).
    pub fn l3_weights(&self) -> &[u16] {
        &self.l3
    }

    /// RAM usage in bytes.
    #[inline]
    pub fn ram_usage(&self) -> usize {
        self.l0.len() * 2
            + self.l1.len() * 2
            + self.l3.len() * 2
            + self.l0_to_l1.len() * 4  // Range<u16> = 2 × u16
            + self.l1_to_l3.len() * 4
            + 4 // count field
    }

    /// Summary string.
    pub fn summary(&self) -> String {
        format!(
            "KnowTree: L0={} groups, L1={} blocks, L3={} chars, ~{}KB",
            self.l0.len(),
            self.l1.len(),
            self.l3.len(),
            self.ram_usage() / 1024,
        )
    }

    /// Serialize to bytes.
    ///
    /// Format:
    /// ```text
    /// [magic:2B "KT"][version:1B][l0_count:1B][l1_count:2B][l3_count:2B]
    /// [l0 p_weights: l0_count × 2B]
    /// [l1 p_weights: l1_count × 2B]
    /// [l3 p_weights: l3_count × 2B]
    /// [l0_to_l1 topology: l0_count × 4B (start:2B, end:2B)]
    /// [l1_to_l3 topology: l1_count × 4B (start:2B, end:2B)]
    /// ```
    pub fn to_bytes(&self) -> Vec<u8> {
        let header_size = 2 + 1 + 1 + 2 + 2; // magic + version + l0_count + l1_count + l3_count
        let data_size = self.l0.len() * 2
            + self.l1.len() * 2
            + self.l3.len() * 2
            + self.l0_to_l1.len() * 4
            + self.l1_to_l3.len() * 4;
        let mut buf = Vec::with_capacity(header_size + data_size);

        // Header
        buf.extend_from_slice(b"KT");           // magic
        buf.push(0x01);                          // version
        buf.push(self.l0.len() as u8);           // l0_count
        buf.extend_from_slice(&(self.l1.len() as u16).to_be_bytes()); // l1_count
        buf.extend_from_slice(&(self.l3.len() as u16).to_be_bytes()); // l3_count

        // L0 P_weights
        for &pw in &self.l0 {
            buf.extend_from_slice(&pw.to_be_bytes());
        }

        // L1 P_weights
        for &pw in &self.l1 {
            buf.extend_from_slice(&pw.to_be_bytes());
        }

        // L3 P_weights
        for &pw in &self.l3 {
            buf.extend_from_slice(&pw.to_be_bytes());
        }

        // L0→L1 topology
        for r in &self.l0_to_l1 {
            buf.extend_from_slice(&r.start.to_be_bytes());
            buf.extend_from_slice(&r.end.to_be_bytes());
        }

        // L1→L3 topology
        for r in &self.l1_to_l3 {
            buf.extend_from_slice(&r.start.to_be_bytes());
            buf.extend_from_slice(&r.end.to_be_bytes());
        }

        buf
    }

    /// Restore from bytes.
    pub fn from_bytes(b: &[u8]) -> Option<Self> {
        if b.len() < 8 {
            return None;
        }
        // Check magic
        if b[0] != b'K' || b[1] != b'T' {
            return None;
        }
        let _version = b[2];
        let l0_count = b[3] as usize;
        let l1_count = u16::from_be_bytes([b[4], b[5]]) as usize;
        let l3_count = u16::from_be_bytes([b[6], b[7]]) as usize;

        let expected_len = 8
            + l0_count * 2
            + l1_count * 2
            + l3_count * 2
            + l0_count * 4
            + l1_count * 4;
        if b.len() < expected_len {
            return None;
        }

        let mut offset = 8;

        // Read L0 P_weights
        let mut l0 = Vec::with_capacity(l0_count);
        for _ in 0..l0_count {
            l0.push(u16::from_be_bytes([b[offset], b[offset + 1]]));
            offset += 2;
        }

        // Read L1 P_weights
        let mut l1 = Vec::with_capacity(l1_count);
        for _ in 0..l1_count {
            l1.push(u16::from_be_bytes([b[offset], b[offset + 1]]));
            offset += 2;
        }

        // Read L3 P_weights
        let mut l3 = Vec::with_capacity(l3_count);
        for _ in 0..l3_count {
            l3.push(u16::from_be_bytes([b[offset], b[offset + 1]]));
            offset += 2;
        }

        // Read L0→L1 topology
        let mut l0_to_l1 = Vec::with_capacity(l0_count);
        for _ in 0..l0_count {
            let start = u16::from_be_bytes([b[offset], b[offset + 1]]);
            let end = u16::from_be_bytes([b[offset + 2], b[offset + 3]]);
            l0_to_l1.push(start..end);
            offset += 4;
        }

        // Read L1→L3 topology
        let mut l1_to_l3 = Vec::with_capacity(l1_count);
        for _ in 0..l1_count {
            let start = u16::from_be_bytes([b[offset], b[offset + 1]]);
            let end = u16::from_be_bytes([b[offset + 2], b[offset + 3]]);
            l1_to_l3.push(start..end);
            offset += 4;
        }

        let count = l3.iter().filter(|&&pw| pw != 0).count() as u32;

        Some(Self {
            l0,
            l1,
            l3,
            l0_to_l1,
            l1_to_l3,
            count,
        })
    }
}

impl Default for KnowTree {
    fn default() -> Self {
        Self::new()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// AliasTable — UTF-32 alias lookup, tách riêng khỏi KnowTree (T15)
// ─────────────────────────────────────────────────────────────────────────────

/// Alias table — maps UTF-32 codepoints to packed P_weight u16.
///
/// Separated from KnowTree per T15 spec. Contains ~33K emoji/UTF-32 entries
/// that are NOT in L0 UCD_TABLE. Each entry: (cp: u32, p_weight: u16) = 6 bytes.
///
/// ```text
/// Lookup: alias_table.get(cp) → u16 P_weight   O(log n) binary search
/// Size:   ~33K entries × 6B = ~198 KB (static, zero-copy)
/// Source: json/udc_utf32_compact.json (generated at build time by ucd/build.rs)
/// ```
///
/// For L0 codepoints (8,846 entries), use `KnowTree::get()` instead.
/// For combined lookup, use `AliasTable::get_full()` which checks both.
pub struct AliasTable {
    /// Marker to prevent direct construction; all data is in ucd statics.
    _private: (),
}

impl AliasTable {
    /// Create an AliasTable handle.
    ///
    /// No allocation — all data lives in ucd's static tables generated at build time.
    pub fn new() -> Self {
        Self { _private: () }
    }

    /// Lookup P_weight for a codepoint in the alias table only.
    ///
    /// Returns 0 if codepoint not found. O(log n).
    #[inline]
    pub fn get(&self, cp: u32) -> u16 {
        ucd::alias_p_weight(cp)
    }

    /// Lookup Molecule for a codepoint in the alias table.
    #[inline]
    pub fn get_mol(&self, cp: u32) -> Option<Molecule> {
        let pw = self.get(cp);
        if pw != 0 {
            Some(Molecule::from_u16(pw))
        } else {
            None
        }
    }

    /// Full lookup: tries L0 UCD_TABLE first, then alias table.
    ///
    /// Returns 0 only if codepoint is in neither table.
    #[inline]
    pub fn get_full(&self, cp: u32) -> u16 {
        ucd::p_weight_full(cp)
    }

    /// Full Molecule lookup across both tables.
    #[inline]
    pub fn get_mol_full(&self, cp: u32) -> Option<Molecule> {
        let pw = self.get_full(cp);
        if pw != 0 {
            Some(Molecule::from_u16(pw))
        } else {
            None
        }
    }

    /// Check if codepoint exists in alias table.
    #[inline]
    pub fn contains(&self, cp: u32) -> bool {
        self.get(cp) != 0
    }

    /// Number of entries in alias table.
    #[inline]
    pub fn len(&self) -> usize {
        ucd::alias_table_len()
    }

    /// Whether alias table is empty.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// RAM usage — zero (static data, no heap allocation).
    #[inline]
    pub fn ram_usage(&self) -> usize {
        0 // all data in static tables
    }

    /// Summary string.
    pub fn summary(&self) -> String {
        format!(
            "AliasTable: {} entries, ~{}KB (static)",
            self.len(),
            (self.len() * 6) / 1024,
        )
    }
}

impl Default for AliasTable {
    fn default() -> Self {
        Self::new()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// KnowTreeLegacy — old TieredStore wrapper (T10 sẽ xóa)
// ─────────────────────────────────────────────────────────────────────────────

/// Legacy knowledge tree — L2-Ln storage powered by TieredStore.
///
/// DEPRECATED: Sẽ bị xóa ở T10. Dùng `KnowTree` (v2) thay thế.
pub struct KnowTreeLegacy {
    /// Underlying tiered storage
    store: TieredStore,
    /// Total sentences stored
    sentences_stored: u64,
    /// Total concepts stored
    concepts_stored: u64,
    /// Total promotions from STM
    promotions: u64,
}

impl KnowTreeLegacy {
    /// Create for PC (610 page cache, 8192 dict).
    pub fn for_pc() -> Self {
        Self {
            store: TieredStore::for_pc(),
            sentences_stored: 0,
            concepts_stored: 0,
            promotions: 0,
        }
    }

    /// Create for mobile (233 page cache, 4096 dict).
    pub fn for_mobile() -> Self {
        Self {
            store: TieredStore::for_mobile(),
            sentences_stored: 0,
            concepts_stored: 0,
            promotions: 0,
        }
    }

    /// Create for embedded (55 page cache, 256 dict).
    pub fn for_embedded() -> Self {
        Self {
            store: TieredStore::for_embedded(),
            sentences_stored: 0,
            concepts_stored: 0,
            promotions: 0,
        }
    }

    /// Create custom.
    pub fn new(cache_capacity: usize, dict_capacity: usize) -> Self {
        Self {
            store: TieredStore::new(cache_capacity, dict_capacity),
            sentences_stored: 0,
            concepts_stored: 0,
            promotions: 0,
        }
    }

    // ── Store operations ─────────────────────────────────────────────────────

    /// Store a sentence as L2 node.
    ///
    /// Returns chain_hash of the stored node.
    /// Also creates silk edges between consecutive words.
    pub fn store_sentence(
        &mut self,
        chain: &MolecularChain,
        parent: Option<&MolecularChain>,
        word_hashes: &[u64],
        ts: i64,
    ) -> u64 {
        let hash = self.store.store_node(chain, parent, 2, ts);
        self.sentences_stored += 1;

        // Create silk edges between consecutive word hashes
        if word_hashes.len() >= 2 {
            for w in word_hashes.windows(2) {
                self.store
                    .store_edge(w[0], w[1], 0.6, RelationBase::Compose.as_byte(), 2);
            }
        }

        // Edge from sentence node to each word (Member relation)
        for &wh in word_hashes {
            self.store
                .store_edge(hash, wh, 0.5, RelationBase::Member.as_byte(), 2);
        }

        hash
    }

    /// Store a concept (LCA result) as L3+ node.
    ///
    /// `sources` = hashes of L2 nodes that were clustered.
    pub fn store_concept(
        &mut self,
        chain: &MolecularChain,
        parent: Option<&MolecularChain>,
        layer: u8,
        sources: &[u64],
        ts: i64,
    ) -> u64 {
        let layer = layer.max(3); // concepts are L3+
        let hash = self.store.store_node(chain, parent, layer, ts);
        self.concepts_stored += 1;

        // Edges from concept to sources (DerivedFrom)
        for &src in sources {
            self.store
                .store_edge(hash, src, 0.7, RelationBase::DerivedFrom.as_byte(), layer);
        }

        hash
    }

    /// Promote an STM observation to L2 node.
    ///
    /// Called when Dream cycle approves promotion.
    pub fn promote_from_stm(
        &mut self,
        chain: &MolecularChain,
        parent: Option<&MolecularChain>,
        fire_count: u32,
        ts: i64,
    ) -> u64 {
        let hash = self.store.store_node(chain, parent, 2, ts);
        self.promotions += 1;

        // Weight proportional to fire_count (capped at 1.0)
        let _weight = (fire_count as f32 / 10.0).min(1.0);

        hash
    }

    // ── Query operations ─────────────────────────────────────────────────────

    /// Lookup node by hash in a specific layer.
    pub fn lookup(&mut self, hash: u64, layer: u8) -> Option<&CompactNode> {
        self.store.lookup(hash, layer)
    }

    /// Lookup node + follow silk edges (depth limited).
    pub fn query(&mut self, hash: u64, layer: u8, depth: u8) -> Option<NodeWithEdges> {
        self.store.lookup_with_edges(hash, layer, depth)
    }

    /// Search by text hash (FNV-1a of lowercase text).
    /// Searches L2 first, returns None if not found in L2 or L3.
    pub fn search_text(&mut self, text: &str, layer: u8) -> Option<&CompactNode> {
        let hash = fnv1a_str(text);
        self.store.lookup(hash, layer)
    }

    // ── Batch operations ─────────────────────────────────────────────────────

    /// Store multiple sentences from a book chapter.
    ///
    /// Returns hashes of all stored sentence nodes.
    pub fn store_chapter(
        &mut self,
        chains: &[(MolecularChain, Vec<u64>)], // (sentence_chain, word_hashes)
        chapter_chain: Option<&MolecularChain>,
        ts: i64,
    ) -> Vec<u64> {
        let mut hashes = Vec::with_capacity(chains.len());
        let mut prev_hash = 0u64;

        for (chain, word_hashes) in chains {
            let hash = self.store_sentence(chain, chapter_chain, word_hashes, ts);
            hashes.push(hash);

            // Sequential edge (sentence → next sentence)
            if prev_hash != 0 {
                self.store
                    .store_edge(prev_hash, hash, 0.4, RelationBase::Causes.as_byte(), 2);
            }
            prev_hash = hash;
        }

        hashes
    }

    // ── Restore from origin.olang ──────────────────────────────────────────

    /// Restore a compact node from origin.olang bytes — boot path.
    ///
    /// QT8: origin.olang = bộ nhớ duy nhất, RAM = cache.
    pub fn restore_compact_node(&mut self, data: &[u8]) {
        if let Some(node) = CompactNode::from_bytes(data) {
            self.store.restore_node(node);
        }
    }

    // ── Stats ────────────────────────────────────────────────────────────────

    /// Total nodes across all layers.
    pub fn total_nodes(&self) -> u64 {
        self.store.total_nodes()
    }

    /// Total edges.
    pub fn total_edges(&self) -> u64 {
        self.store.total_edges()
    }

    /// Sentences stored (L2).
    pub fn sentences(&self) -> u64 {
        self.sentences_stored
    }

    /// Concepts stored (L3+).
    pub fn concepts(&self) -> u64 {
        self.concepts_stored
    }

    /// Promotions from STM.
    pub fn promotions(&self) -> u64 {
        self.promotions
    }

    /// RAM usage estimate.
    pub fn ram_usage(&self) -> usize {
        self.store.ram_usage()
    }

    /// Disk usage estimate.
    pub fn disk_usage(&self) -> usize {
        self.store.disk_usage()
    }

    /// Cache hit rate.
    pub fn cache_hit_rate(&self) -> f32 {
        self.store.cache.hit_rate()
    }

    /// Summary.
    pub fn summary(&self) -> String {
        format!(
            "KnowTree: {} sentences + {} concepts + {} promotions\n\
             Nodes: {} | Edges: {} | RAM: ~{}KB | Disk: ~{}KB\n\
             Cache: {:.1}% hit rate",
            self.sentences_stored,
            self.concepts_stored,
            self.promotions,
            self.store.total_nodes(),
            self.store.total_edges(),
            self.ram_usage() / 1024,
            self.disk_usage() / 1024,
            self.cache_hit_rate() * 100.0,
        )
    }

    /// Mutable access to underlying store (for advanced operations).
    pub fn store_mut(&mut self) -> &mut TieredStore {
        &mut self.store
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// SlimKnowTree — spec-compliant ~10 bytes per node
// ─────────────────────────────────────────────────────────────────────────────

/// SlimKnowTree — knowledge tree dùng SlimNode/SlimPage.
///
/// Pipeline đúng spec:
/// ```text
/// UCD entry = 5 công thức (L0, bất biến)
///      │
///      ↓  input gọi công thức → tính ra giá trị
///      │
/// Molecule [S][R][V][A][T] = 5 bytes (giá trị tĩnh)
///      │
///      ↓  tagged sparse encoding
///      │
/// [mask:1B][non-defaults:0-5B] = 1-6 bytes
///      │
///      ↓  ghi vào SlimKnowTree
///      │
/// SlimNode [hash:8][tagged_len:1][tagged:1-6] = 10-15 bytes per node
/// SlimPage [header:19][nodes...][edges...][checksum:8]
/// ```
///
/// 500M nodes × 11B avg = 5.5GB → VỪA ĐIỆN THOẠI
pub struct SlimKnowTreeLegacy {
    /// Pages per layer (layer → list of pages)
    pages: Vec<(u8, SlimPage)>,
    /// Hash index: hash → (layer, page_index) for O(1) lookup
    hash_index: BTreeMap<u64, (u8, usize)>,
    /// Current page per layer
    current_page_id: u32,
    /// Stats
    total_nodes: u64,
    total_edges: u64,
    sentences_stored: u64,
    concepts_stored: u64,
    promotions: u64,
}

impl SlimKnowTreeLegacy {
    /// Create new SlimKnowTree.
    pub fn new() -> Self {
        Self {
            pages: Vec::new(),
            hash_index: BTreeMap::new(),
            current_page_id: 0,
            total_nodes: 0,
            total_edges: 0,
            sentences_stored: 0,
            concepts_stored: 0,
            promotions: 0,
        }
    }

    // ── Store operations ────────────────────────────────────────────────────

    /// Store chain as SlimNode in the specified layer.
    ///
    /// Returns chain_hash.
    fn store_slim(&mut self, chain: &MolecularChain, layer: u8, ts: i64) -> u64 {
        let slim = SlimNode::from_chain(chain);
        let hash = slim.hash;

        // Find or create current page for this layer
        let page = self.current_page_mut(layer, ts);
        if page.push_node(slim) {
            // Stored in current page — find its index
            let page_idx = self.pages.len() - 1
                - self.pages.iter().rev().position(|(l, p)| *l == layer && !p.is_full()).unwrap_or(0);
            self.hash_index.insert(hash, (layer, page_idx));
        } else {
            // Page full → create new page
            self.current_page_id += 1;
            let mut new_page = SlimPage::new(self.current_page_id, layer, ts);
            let slim2 = SlimNode::from_chain(chain);
            new_page.push_node(slim2);
            self.pages.push((layer, new_page));
            let page_idx = self.pages.len() - 1;
            self.hash_index.insert(hash, (layer, page_idx));
        }

        self.total_nodes += 1;
        hash
    }

    /// Store edge in the current page for the given layer.
    fn store_edge_slim(&mut self, from: u64, to: u64, weight: f32, relation: u8, layer: u8, ts: i64) {
        let edge = CompactEdge::encode(from, to, weight, relation);
        let page = self.current_page_mut(layer, ts);
        page.push_edge(edge);
        self.total_edges += 1;
    }

    /// Store a sentence as L2 SlimNode.
    pub fn store_sentence(
        &mut self,
        chain: &MolecularChain,
        word_hashes: &[u64],
        ts: i64,
    ) -> u64 {
        let hash = self.store_slim(chain, 2, ts);
        self.sentences_stored += 1;

        // Silk edges between consecutive words
        if word_hashes.len() >= 2 {
            for w in word_hashes.windows(2) {
                self.store_edge_slim(w[0], w[1], 0.6, RelationBase::Compose.as_byte(), 2, ts);
            }
        }
        // Edge from sentence to each word
        for &wh in word_hashes {
            self.store_edge_slim(hash, wh, 0.5, RelationBase::Member.as_byte(), 2, ts);
        }

        hash
    }

    /// Store a concept (LCA result) as L3+ SlimNode.
    pub fn store_concept(
        &mut self,
        chain: &MolecularChain,
        layer: u8,
        sources: &[u64],
        ts: i64,
    ) -> u64 {
        let layer = layer.max(3);
        let hash = self.store_slim(chain, layer, ts);
        self.concepts_stored += 1;

        for &src in sources {
            self.store_edge_slim(hash, src, 0.7, RelationBase::DerivedFrom.as_byte(), layer, ts);
        }

        hash
    }

    /// Promote STM observation to L2 SlimNode.
    pub fn promote_from_stm(
        &mut self,
        chain: &MolecularChain,
        ts: i64,
    ) -> u64 {
        let hash = self.store_slim(chain, 2, ts);
        self.promotions += 1;
        hash
    }

    // ── Query operations ────────────────────────────────────────────────────

    /// Lookup SlimNode by hash in a specific layer — O(1) via hash index.
    pub fn lookup(&self, hash: u64, layer: u8) -> Option<&SlimNode> {
        // Fast path: hash index
        if let Some(&(l, page_idx)) = self.hash_index.get(&hash) {
            if l == layer {
                if let Some((_, page)) = self.pages.get(page_idx) {
                    return page.find_node(hash);
                }
            }
        }
        // Fallback: linear scan (for restored nodes without index)
        for (l, page) in &self.pages {
            if *l == layer {
                if let Some(node) = page.find_node(hash) {
                    return Some(node);
                }
            }
        }
        None
    }

    /// Lookup and decode to MolecularChain.
    pub fn lookup_chain(&self, hash: u64, layer: u8) -> Option<MolecularChain> {
        self.lookup(hash, layer)?.to_chain()
    }

    /// Search by text hash.
    pub fn search_text(&self, text: &str, layer: u8) -> Option<&SlimNode> {
        let hash = fnv1a_str(text);
        self.lookup(hash, layer)
    }

    // ── Batch operations ────────────────────────────────────────────────────

    /// Store chapter (batch of sentences).
    pub fn store_chapter(
        &mut self,
        chains: &[(MolecularChain, Vec<u64>)],
        ts: i64,
    ) -> Vec<u64> {
        let mut hashes = Vec::with_capacity(chains.len());
        let mut prev_hash = 0u64;

        for (chain, word_hashes) in chains {
            let hash = self.store_sentence(chain, word_hashes, ts);
            hashes.push(hash);

            if prev_hash != 0 {
                self.store_edge_slim(prev_hash, hash, 0.4, RelationBase::Causes.as_byte(), 2, ts);
            }
            prev_hash = hash;
        }

        hashes
    }

    // ── Restore from origin.olang ──────────────────────────────────────────

    /// Restore a SlimNode from origin.olang record 0x0A — boot path.
    ///
    /// QT8: origin.olang = bộ nhớ duy nhất, RAM = cache tạm.
    pub fn restore_slim_node(&mut self, hash: u64, tagged: &[u8], layer: u8, ts: i64) {
        let slim = SlimNode {
            hash,
            tagged: tagged.to_vec(),
        };

        let page = self.current_page_mut(layer, ts);
        if page.push_node(slim) {
            let page_idx = self.pages.len() - 1
                - self.pages.iter().rev().position(|(l, p)| *l == layer && !p.is_full()).unwrap_or(0);
            self.hash_index.insert(hash, (layer, page_idx));
        } else {
            self.current_page_id += 1;
            let mut new_page = SlimPage::new(self.current_page_id, layer, ts);
            new_page.push_node(SlimNode {
                hash,
                tagged: tagged.to_vec(),
            });
            self.pages.push((layer, new_page));
            let page_idx = self.pages.len() - 1;
            self.hash_index.insert(hash, (layer, page_idx));
        }

        self.total_nodes += 1;
    }

    // ── Serialization ───────────────────────────────────────────────────────

    /// Serialize all pages → bytes (for origin.olang record 0x08).
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        let page_count = self.pages.len() as u32;
        buf.extend_from_slice(&page_count.to_be_bytes());
        for (_, page) in &self.pages {
            let page_bytes = page.to_bytes();
            buf.extend_from_slice(&(page_bytes.len() as u32).to_be_bytes());
            buf.extend_from_slice(&page_bytes);
        }
        buf
    }

    /// Restore from bytes.
    pub fn restore_from_bytes(&mut self, b: &[u8]) -> bool {
        if b.len() < 4 {
            return false;
        }
        let page_count = u32::from_be_bytes([b[0], b[1], b[2], b[3]]) as usize;
        let mut offset = 4;

        for _ in 0..page_count {
            if offset + 4 > b.len() {
                return false;
            }
            let page_len = u32::from_be_bytes(
                b[offset..offset + 4].try_into().unwrap_or([0; 4]),
            ) as usize;
            offset += 4;

            if offset + page_len > b.len() {
                return false;
            }
            if let Some(page) = SlimPage::from_bytes(&b[offset..offset + page_len]) {
                let layer = page.layer;
                self.total_nodes += page.nodes.len() as u64;
                self.total_edges += page.edges.len() as u64;
                self.pages.push((layer, page));
            }
            offset += page_len;
        }
        true
    }

    // ── Stats ───────────────────────────────────────────────────────────────

    /// Total nodes.
    pub fn total_nodes(&self) -> u64 {
        self.total_nodes
    }

    /// Total edges.
    pub fn total_edges(&self) -> u64 {
        self.total_edges
    }

    /// Sentences stored.
    pub fn sentences(&self) -> u64 {
        self.sentences_stored
    }

    /// Concepts stored.
    pub fn concepts(&self) -> u64 {
        self.concepts_stored
    }

    /// Promotions from STM.
    pub fn promotions(&self) -> u64 {
        self.promotions
    }

    /// Average bytes per node across all pages.
    pub fn avg_bytes_per_node(&self) -> f32 {
        if self.total_nodes == 0 {
            return 0.0;
        }
        let total_bytes: usize = self.pages.iter().map(|(_, p)| {
            p.nodes.iter().map(|n| n.total_size()).sum::<usize>()
        }).sum();
        total_bytes as f32 / self.total_nodes as f32
    }

    /// Summary.
    pub fn summary(&self) -> String {
        format!(
            "SlimKnowTreeLegacy: {} sentences + {} concepts + {} promotions\n\
             Nodes: {} | Edges: {} | Pages: {} | Avg: {:.1}B/node",
            self.sentences_stored,
            self.concepts_stored,
            self.promotions,
            self.total_nodes,
            self.total_edges,
            self.pages.len(),
            self.avg_bytes_per_node(),
        )
    }

    // ── Internal ────────────────────────────────────────────────────────────

    fn current_page_mut(&mut self, layer: u8, ts: i64) -> &mut SlimPage {
        // Find existing non-full page for this layer
        let has_page = self.pages.iter().any(|(l, p)| *l == layer && !p.is_full());

        if !has_page {
            self.current_page_id += 1;
            let page = SlimPage::new(self.current_page_id, layer, ts);
            self.pages.push((layer, page));
        }

        // Return mutable reference to the last non-full page for this layer
        self.pages
            .iter_mut()
            .rev()
            .find(|(l, p)| *l == layer && !p.is_full())
            .map(|(_, p)| p)
            .unwrap()
    }
}

impl Default for SlimKnowTreeLegacy {
    fn default() -> Self {
        Self::new()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper: text → word hashes
// ─────────────────────────────────────────────────────────────────────────────

/// Extract word hashes from text (for silk edge creation).
pub fn text_to_word_hashes(text: &str) -> Vec<u64> {
    text.split_whitespace()
        .filter(|w| w.chars().count() > 2) // skip short words
        .map(|w| fnv1a_str(&w.to_lowercase()))
        .collect()
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::molecular::{Molecule, ShapeBase, TimeDim};

    fn test_chain(v: u8) -> MolecularChain {
        MolecularChain::single(Molecule::raw(
            ShapeBase::Sphere.as_byte(),
            RelationBase::Member.as_byte(),
            v,
            0x80,
            TimeDim::Medium.as_byte(),
        ))
    }

    #[test]
    fn knowtree_store_sentence() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        let chain = test_chain(0x80);
        let words = alloc::vec![0xAAAA, 0xBBBB, 0xCCCC];
        let hash = kt.store_sentence(&chain, None, &words, 1000);
        assert!(hash != 0);
        assert_eq!(kt.sentences(), 1);
        // 2 word-word edges + 3 sentence-word edges = 5
        assert_eq!(kt.total_edges(), 5);
    }

    #[test]
    fn knowtree_store_concept() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        let chain = test_chain(0x90);
        let sources = alloc::vec![0x1111, 0x2222, 0x3333];
        let hash = kt.store_concept(&chain, None, 3, &sources, 1000);
        assert!(hash != 0);
        assert_eq!(kt.concepts(), 1);
        assert_eq!(kt.total_edges(), 3); // 3 DerivedFrom edges
    }

    #[test]
    fn knowtree_promote() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        let chain = test_chain(0xA0);
        let hash = kt.promote_from_stm(&chain, None, 5, 1000);
        assert!(hash != 0);
        assert_eq!(kt.promotions(), 1);
    }

    #[test]
    fn knowtree_lookup() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        let chain = test_chain(0x80);
        let hash = kt.store_sentence(&chain, None, &[], 1000);

        let found = kt.lookup(hash, 2);
        assert!(found.is_some(), "Should find L2 node");
    }

    #[test]
    fn knowtree_query_with_edges() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        let c1 = test_chain(0x80);
        let c2 = test_chain(0x90);
        let h1 = kt.store_sentence(&c1, None, &[], 1000);
        let _h2 = kt.store_sentence(&c2, None, &[], 1001);
        kt.store_mut()
            .store_edge(h1, _h2, 0.8, RelationBase::Similar.as_byte(), 2);

        let result = kt.query(h1, 2, 1);
        assert!(result.is_some());
    }

    #[test]
    fn knowtree_store_chapter() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        let chains: Vec<(MolecularChain, Vec<u64>)> = (0u8..5)
            .map(|i| {
                (
                    test_chain(0x80 + i),
                    alloc::vec![i as u64 * 100, i as u64 * 100 + 1],
                )
            })
            .collect();

        let hashes = kt.store_chapter(&chains, None, 1000);
        assert_eq!(hashes.len(), 5);
        assert_eq!(kt.sentences(), 5);
        // Each sentence: 1 word-word + 2 sentence-word = 3 edges
        // Sequential: 4 sentence→sentence edges
        // Total: 5×3 + 4 = 19
        assert_eq!(kt.total_edges(), 19);
    }

    #[test]
    fn knowtree_summary() {
        let kt = KnowTreeLegacy::new(4, 100);
        let s = kt.summary();
        assert!(s.contains("KnowTree"), "{}", s);
        assert!(s.contains("0 sentences"), "{}", s);
    }

    #[test]
    fn knowtree_for_pc() {
        let kt = KnowTreeLegacy::for_pc();
        assert_eq!(kt.total_nodes(), 0); // freshly created, no nodes
    }

    #[test]
    fn text_to_word_hashes_basic() {
        let hashes = text_to_word_hashes("tôi buồn vì mất việc");
        // "tôi" = 3 chars, "buồn" = 4, "vì" = 2 (skip), "mất" = 3, "việc" = 4
        assert_eq!(hashes.len(), 4, "Skip 2-char words");
        // All unique
        let mut unique = hashes.clone();
        unique.sort();
        unique.dedup();
        assert_eq!(unique.len(), hashes.len(), "All hashes unique");
    }

    #[test]
    fn text_to_word_hashes_deterministic() {
        let h1 = text_to_word_hashes("hello world");
        let h2 = text_to_word_hashes("hello world");
        assert_eq!(h1, h2, "Deterministic hashing");
    }

    #[test]
    fn knowtree_concept_minimum_layer() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        let chain = test_chain(0x80);
        // Try to store at layer 1 → should be forced to L3
        kt.store_concept(&chain, None, 1, &[], 1000);
        assert_eq!(kt.concepts(), 1);
    }

    #[test]
    fn knowtree_ram_disk_usage() {
        let mut kt = KnowTreeLegacy::new(4, 100);
        for i in 0u8..10 {
            let chain = test_chain(0x80 + i);
            kt.store_sentence(&chain, None, &[], i as i64);
        }
        assert!(kt.ram_usage() > 0);
    }

    // ── SlimKnowTreeLegacy ─────────────────────────────────────────────────

    use super::SlimKnowTreeLegacy;

    #[test]
    fn slim_knowtree_store_sentence() {
        let mut skt = SlimKnowTreeLegacy::new();
        let chain = test_chain(0x80);
        let words = alloc::vec![0xAAAAu64, 0xBBBB, 0xCCCC];
        let hash = skt.store_sentence(&chain, &words, 1000);
        assert!(hash != 0);
        assert_eq!(skt.sentences(), 1);
        assert_eq!(skt.total_nodes(), 1);
        // 2 word-word + 3 sentence-word = 5 edges
        assert_eq!(skt.total_edges(), 5);
    }

    #[test]
    fn slim_knowtree_store_concept() {
        let mut skt = SlimKnowTreeLegacy::new();
        let chain = test_chain(0x90);
        let sources = alloc::vec![0x1111u64, 0x2222, 0x3333];
        let hash = skt.store_concept(&chain, 3, &sources, 1000);
        assert!(hash != 0);
        assert_eq!(skt.concepts(), 1);
        assert_eq!(skt.total_edges(), 3);
    }

    #[test]
    fn slim_knowtree_promote() {
        let mut skt = SlimKnowTreeLegacy::new();
        let chain = test_chain(0xA0);
        let hash = skt.promote_from_stm(&chain, 1000);
        assert!(hash != 0);
        assert_eq!(skt.promotions(), 1);
    }

    #[test]
    fn slim_knowtree_lookup() {
        let mut skt = SlimKnowTreeLegacy::new();
        let chain = test_chain(0x80);
        let hash = skt.store_sentence(&chain, &[], 1000);

        let found = skt.lookup(hash, 2);
        assert!(found.is_some(), "Should find L2 slim node");
        assert_eq!(found.unwrap().hash, hash);
    }

    #[test]
    fn slim_knowtree_lookup_chain() {
        let mut skt = SlimKnowTreeLegacy::new();
        let chain = test_chain(0xB0);
        let hash = skt.store_sentence(&chain, &[], 1000);

        let decoded = skt.lookup_chain(hash, 2);
        assert!(decoded.is_some());
        assert_eq!(decoded.unwrap(), chain);
    }

    #[test]
    fn slim_knowtree_store_chapter() {
        let mut skt = SlimKnowTreeLegacy::new();
        let chains: Vec<(MolecularChain, Vec<u64>)> = (0u8..5)
            .map(|i| {
                (
                    test_chain(0x80 + i),
                    alloc::vec![i as u64 * 100, i as u64 * 100 + 1],
                )
            })
            .collect();

        let hashes = skt.store_chapter(&chains, 1000);
        assert_eq!(hashes.len(), 5);
        assert_eq!(skt.sentences(), 5);
        // Each: 1 word-word + 2 sentence-word = 3. Sequential: 4.
        // Total: 5×3 + 4 = 19
        assert_eq!(skt.total_edges(), 19);
    }

    #[test]
    fn slim_knowtree_serialization_roundtrip() {
        let mut skt = SlimKnowTreeLegacy::new();
        for i in 0u8..10 {
            let chain = test_chain(0x80 + i);
            skt.store_sentence(&chain, &[], i as i64);
        }

        let bytes = skt.to_bytes();
        let mut restored = SlimKnowTreeLegacy::new();
        assert!(restored.restore_from_bytes(&bytes));
        assert_eq!(restored.total_nodes(), 10);
    }

    #[test]
    fn slim_knowtree_avg_bytes_per_node() {
        let mut skt = SlimKnowTreeLegacy::new();
        for i in 0u8..50 {
            let chain = test_chain(0x80 + (i % 20));
            skt.store_sentence(&chain, &[], i as i64);
        }
        let avg = skt.avg_bytes_per_node();
        // SlimNode: hash:8 + len:1 + tagged:2-3 = ~11-12 bytes
        assert!(
            avg <= 15.0,
            "Average {:.1}B/node should be ≤ 15B",
            avg
        );
    }

    #[test]
    fn slim_knowtree_summary() {
        let skt = SlimKnowTreeLegacy::new();
        let s = skt.summary();
        assert!(s.contains("SlimKnowTreeLegacy"), "{}", s);
    }

    #[test]
    fn slim_knowtree_concept_minimum_layer() {
        let mut skt = SlimKnowTreeLegacy::new();
        let chain = test_chain(0x80);
        // Try layer 1 → forced to L3
        skt.store_concept(&chain, 1, &[], 1000);
        assert_eq!(skt.concepts(), 1);
        // Should be findable at layer 3
        let hash = chain.chain_hash();
        assert!(skt.lookup(hash, 3).is_some());
    }

    // ── KnowTree hierarchical (T14) ─────────────────────────────────────

    #[test]
    fn knowtree_new_empty() {
        let kt = KnowTree::new();
        assert_eq!(kt.count(), 0);
        assert_eq!(kt.group_count(), 0);
        assert_eq!(kt.block_count(), 0);
    }

    #[test]
    fn knowtree_bootstrap_structure() {
        let kt = KnowTree::bootstrap_from_ucd();
        // Must have 4 groups (SDF, MATH, EMOTICON, MUSICAL)
        assert_eq!(kt.group_count(), 4, "Must have 4 groups");
        // Must have blocks (spec says ~59)
        assert!(kt.block_count() > 0, "Must have blocks");
        // Must have leaf entries
        assert!(kt.count() > 0, "Must have leaf entries");
    }

    #[test]
    fn knowtree_bootstrap_lookup_matches_ucd() {
        let kt = KnowTree::bootstrap_from_ucd();
        // FIRE emoji — must match ucd::p_weight_of
        let fire_pw = kt.get(0x1F525);
        assert_eq!(fire_pw, ucd::p_weight_of(0x1F525), "FIRE p_weight must match UCD");
        assert!(fire_pw != 0, "FIRE should have nonzero p_weight");
        // Unknown codepoint
        assert_eq!(kt.get(0x0041), 0, "Latin A not in 4 groups");
    }

    #[test]
    fn knowtree_bootstrap_get_mol() {
        let kt = KnowTree::bootstrap_from_ucd();
        let mol = kt.get_mol(0x1F525);
        assert!(mol.is_some(), "FIRE should produce Molecule");
        assert!(kt.get_mol(0x0041).is_none(), "Latin A should be None");
    }

    #[test]
    fn knowtree_bootstrap_contains() {
        let kt = KnowTree::bootstrap_from_ucd();
        assert!(kt.contains(0x1F525), "FIRE must be contained");
        assert!(!kt.contains(0x0041), "Latin A not contained");
    }

    #[test]
    fn knowtree_group_p_weight() {
        let kt = KnowTree::bootstrap_from_ucd();
        for i in 0..kt.group_count() {
            let pw = kt.group_p_weight(i);
            // Aggregate P_weight should be nonzero for populated groups
            // (mode of children's P_weights)
            assert!(pw != 0 || kt.group_block_range(i).is_empty(),
                "Group {} P_weight should be nonzero if it has blocks", i);
        }
        // Out of range
        assert_eq!(kt.group_p_weight(999), 0);
    }

    #[test]
    fn knowtree_block_p_weight() {
        let kt = KnowTree::bootstrap_from_ucd();
        for i in 0..kt.block_count() {
            let _pw = kt.block_p_weight(i);
            // Just check it doesn't panic
        }
        assert_eq!(kt.block_p_weight(999), 0);
    }

    #[test]
    fn knowtree_topology_consistency() {
        let kt = KnowTree::bootstrap_from_ucd();
        // Every group's block range should be valid
        let mut total_blocks_via_groups = 0u16;
        for gi in 0..kt.group_count() {
            let range = kt.group_block_range(gi);
            assert!(range.start <= range.end, "Group {} range invalid", gi);
            assert!((range.end as usize) <= kt.block_count(),
                "Group {} range.end {} exceeds block_count {}", gi, range.end, kt.block_count());
            total_blocks_via_groups += range.end - range.start;
        }
        assert_eq!(total_blocks_via_groups as usize, kt.block_count(),
            "Sum of group block ranges must equal total blocks");

        // Every block's char range should be valid
        for bi in 0..kt.block_count() {
            let range = kt.block_char_range(bi);
            assert!(range.start <= range.end, "Block {} range invalid", bi);
            assert!((range.end as usize) <= kt.l3.len(),
                "Block {} range.end {} exceeds l3 len {}", bi, range.end, kt.l3.len());
        }
    }

    #[test]
    fn knowtree_ram_usage_under_20kb() {
        let kt = KnowTree::bootstrap_from_ucd();
        let usage = kt.ram_usage();
        // Should be ~18KB, definitely under 20KB
        assert!(usage < 20 * 1024,
            "RAM usage {} should be < 20KB", usage);
    }

    #[test]
    fn knowtree_summary_format() {
        let kt = KnowTree::bootstrap_from_ucd();
        let s = kt.summary();
        assert!(s.contains("KnowTree"), "{}", s);
        assert!(s.contains("groups"), "{}", s);
        assert!(s.contains("blocks"), "{}", s);
    }

    #[test]
    fn knowtree_serialization_roundtrip() {
        let kt = KnowTree::bootstrap_from_ucd();
        let bytes = kt.to_bytes();
        let restored = KnowTree::from_bytes(&bytes).unwrap();

        assert_eq!(restored.group_count(), kt.group_count());
        assert_eq!(restored.block_count(), kt.block_count());
        assert_eq!(restored.count(), kt.count());
        assert_eq!(restored.l3.len(), kt.l3.len());

        // Check a known codepoint
        assert_eq!(restored.get(0x1F525), kt.get(0x1F525));

        // Check topology preserved
        for gi in 0..kt.group_count() {
            assert_eq!(restored.group_p_weight(gi), kt.group_p_weight(gi));
            assert_eq!(restored.group_block_range(gi), kt.group_block_range(gi));
        }
        for bi in 0..kt.block_count() {
            assert_eq!(restored.block_p_weight(bi), kt.block_p_weight(bi));
            assert_eq!(restored.block_char_range(bi), kt.block_char_range(bi));
        }
    }

    #[test]
    fn knowtree_from_bytes_invalid() {
        assert!(KnowTree::from_bytes(&[]).is_none());
        assert!(KnowTree::from_bytes(&[0x00; 4]).is_none()); // bad magic
        assert!(KnowTree::from_bytes(b"KT").is_none()); // too short
    }

    // ── AliasTable (T15) ──────────────────────────────────────────────────

    #[test]
    fn alias_table_populated() {
        let at = super::AliasTable::new();
        assert!(!at.is_empty(), "Alias table should have entries");
        assert!(at.len() > 30_000, "Should have >30K entries, got {}", at.len());
    }

    #[test]
    fn alias_table_lookup() {
        let at = super::AliasTable::new();
        // Latin 'A' (0x0041) should be in alias table, not in L0
        let pw = at.get(0x0041);
        assert!(pw != 0, "Latin A should have nonzero P_weight in alias table");
    }

    #[test]
    fn alias_table_excludes_l0() {
        let at = super::AliasTable::new();
        // FIRE (0x1F525) is L0, should NOT be in alias table
        assert_eq!(at.get(0x1F525), 0, "L0 codepoint should not be in alias table");
    }

    #[test]
    fn alias_table_full_lookup() {
        let at = super::AliasTable::new();
        // L0 codepoint
        assert!(at.get_full(0x1F525) != 0, "FIRE via get_full");
        // Alias codepoint
        assert!(at.get_full(0x0041) != 0, "Latin A via get_full");
    }
}
