//! # compiler — Olang IR → target language
//!
//! OlangProgram (IR opcodes) → C / Rust / WASM text.
//!
//! Pipeline:
//!   OlangIrExpr → compile_expr() → OlangProgram (opcodes)
//!   OlangProgram → Compiler::emit(target) → source code string
//!
//! Targets:
//!   C    — universal, FFI, ARM/x86/embedded via gcc/clang
//!   Rust — native, safe
//!   WASM — text format (.wat), browser/node/server
//!
//! Một backend C = ba platform (C→ARM via cross-compile, C→WASM via emscripten).

#![allow(missing_docs)]
extern crate alloc;
use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;

use crate::ir::{OlangProgram, Op};

// ─────────────────────────────────────────────────────────────────────────────
// Target
// ─────────────────────────────────────────────────────────────────────────────

/// Target language.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(missing_docs)]
pub enum Target {
    C,
    Rust,
    Wasm, // WAT text format
}

impl Target {
    pub fn file_ext(self) -> &'static str {
        match self {
            Self::C => "c",
            Self::Rust => "rs",
            Self::Wasm => "wat",
        }
    }
    pub fn name(self) -> &'static str {
        match self {
            Self::C => "C",
            Self::Rust => "Rust",
            Self::Wasm => "WASM (WAT)",
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// CompileError
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
#[allow(missing_docs)]
pub struct CompileError {
    pub message: String,
    pub op_idx: usize,
}

// ─────────────────────────────────────────────────────────────────────────────
// Compiler
// ─────────────────────────────────────────────────────────────────────────────

/// Compiler: OlangProgram → source code string.
pub struct Compiler {
    pub target: Target,
}

impl Compiler {
    pub fn new(target: Target) -> Self {
        Self { target }
    }

    /// Compile OlangProgram → source code.
    pub fn emit(&self, prog: &OlangProgram) -> Result<String, CompileError> {
        match self.target {
            Target::C => emit_c(prog),
            Target::Rust => emit_rust(prog),
            Target::Wasm => emit_wat(prog),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// C backend
// ─────────────────────────────────────────────────────────────────────────────

/// Collect all jump target positions from a program.
fn collect_jump_targets(prog: &OlangProgram) -> Vec<usize> {
    let mut targets = Vec::new();
    for op in &prog.ops {
        match op {
            Op::Jmp(t) | Op::Jz(t) | Op::TryBegin(t) => {
                if !targets.contains(t) {
                    targets.push(*t);
                }
            }
            _ => {}
        }
    }
    targets
}

fn emit_c(prog: &OlangProgram) -> Result<String, CompileError> {
    let mut out = String::new();
    let targets = collect_jump_targets(prog);

    // Header
    out.push_str("/* generated by olang compiler */\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <string.h>\n\n");

    // Runtime types
    out.push_str("typedef uint64_t Chain;\n");
    out.push_str("typedef struct { Chain data[32]; int top; } Stack;\n\n");

    // Runtime helpers
    out.push_str("static void push(Stack *s, Chain v) { s->data[s->top++] = v; }\n");
    out.push_str("static Chain pop(Stack *s) { return s->data[--s->top]; }\n");
    out.push_str("static Chain peek(Stack *s) { return s->data[s->top-1]; }\n");
    out.push_str("/* lca: LCA of two molecular chains */\n");
    out.push_str("extern Chain olang_lca(Chain a, Chain b);\n");
    out.push_str("extern Chain olang_load(const char *name);\n");
    out.push_str("extern void  olang_emit(Chain c);\n");
    out.push_str("extern void  olang_edge(Chain a, Chain b, uint8_t rel);\n");
    out.push_str("extern void  olang_query(Chain a, uint8_t rel);\n");
    out.push_str("/* Device I/O: Olang → HAL → hardware */\n");
    out.push_str("extern int   olang_device_write(const char *id, uint8_t value);\n");
    out.push_str("extern Chain olang_device_read(const char *id);\n");
    out.push_str("extern void  olang_device_list(void);\n\n");

    // Function body
    out.push_str(&format!("void {}(void) {{\n", prog.name.replace(' ', "_")));
    out.push_str("  Stack s = {.top = 0};\n");
    // Try/catch: error flag for setjmp-style recovery
    if prog.ops.iter().any(|op| matches!(op, Op::TryBegin(_))) {
        out.push_str("  int _err = 0;\n");
    }

    for (i, op) in prog.ops.iter().enumerate() {
        // Emit label if this position is a jump target
        if targets.contains(&i) {
            out.push_str(&format!("label_{}:\n", i));
        }
        let line = c_op(op, i)?;
        if !line.is_empty() {
            out.push_str("  ");
            out.push_str(&line);
            out.push('\n');
        }
    }
    // Label after last op for jumps past end
    let end = prog.ops.len();
    if targets.contains(&end) {
        out.push_str(&format!("label_{}:;\n", end));
    }

    out.push_str("}\n");
    Ok(out)
}

fn c_op(op: &Op, _idx: usize) -> Result<String, CompileError> {
    Ok(match op {
        Op::Push(chain) => format!("push(&s, 0x{:016X}ULL); /* chain */", chain.chain_hash()),
        Op::Load(name) => format!("push(&s, olang_load(\"{}\"));", escape(name)),
        Op::Lca => "{ Chain b = pop(&s), a = pop(&s); push(&s, olang_lca(a, b)); }".into(),
        Op::Edge(rel) => format!(
            "{{ Chain b = pop(&s), a = pop(&s); olang_edge(a, b, 0x{:02X}); }}",
            rel
        ),
        Op::Query(rel) => format!("{{ Chain a = pop(&s); olang_query(a, 0x{:02X}); }}", rel),
        Op::Emit => "olang_emit(pop(&s));".into(),
        Op::Dup => "push(&s, peek(&s));".into(),
        Op::Pop => "pop(&s);".into(),
        Op::Swap => "{ Chain b = pop(&s), a = pop(&s); push(&s, b); push(&s, a); }".into(),
        Op::Jmp(target) => format!("goto label_{};", target),
        Op::Jz(target) => format!("if (pop(&s) == 0) goto label_{};", target),
        Op::Loop(n) => format!("for (int _i=0; _i<{}; _i++) {{", n),
        Op::Call(name) => format!("{}();", name.replace(' ', "_")),
        Op::Ret => "return;".into(),
        Op::Halt => "return;".into(),
        Op::Dream => "/* dream */".into(),
        Op::Stats => "/* stats */".into(),
        Op::Nop => "".into(),
        Op::Store(name) => format!("olang_store(\"{}\", pop(&s));", escape(name)),
        Op::StoreUpdate(name) => format!("olang_store_update(\"{}\", pop(&s));", escape(name)),
        Op::LoadLocal(name) => format!("push(&s, olang_load_local(\"{}\"));", escape(name)),
        Op::PushNum(n) => format!("push(&s, (Chain){:.17e});", n),
        Op::Fuse => "/* QT2: FUSE — verify chain finite */ { Chain c = peek(&s); if (c == 0) pop(&s); }".into(),
        Op::ScopeBegin => "{ /* scope begin */".into(),
        Op::ScopeEnd => "} /* scope end */".into(),
        Op::Trace => "fprintf(stderr, \"[TRACE] pc=%d depth=%zu\\n\", __LINE__, s.top);".into(),
        Op::Inspect => "{ Chain c = peek(&s); fprintf(stderr, \"[INSPECT] hash=0x%016llX depth=%zu\\n\", (unsigned long long)c, s.top); }".into(),
        Op::Assert => "if (peek(&s) == 0) { fprintf(stderr, \"[ASSERT FAILED] at line %d\\n\", __LINE__); return; }".into(),
        Op::TypeOf => "{ Chain c = pop(&s); fprintf(stderr, \"[TYPEOF] 0x%016llX\\n\", (unsigned long long)c); push(&s, c); }".into(),
        Op::Why => "{ Chain b = pop(&s); Chain a = peek(&s); fprintf(stderr, \"[WHY] 0x%llX <-> 0x%llX\\n\", (unsigned long long)a, (unsigned long long)b); }".into(),
        Op::Explain => "{ Chain c = peek(&s); fprintf(stderr, \"[EXPLAIN] 0x%016llX\\n\", (unsigned long long)c); }".into(),
        Op::PushMol(s, r, v, a, t) => format!(
            "push(&s, olang_mol(0x{:02X},0x{:02X},0x{:02X},0x{:02X},0x{:02X}));",
            s, r, v, a, t
        ),
        Op::TryBegin(target) => format!("_err = 0; /* try: on error goto label_{} */", target),
        Op::CatchEnd => "_err = 0; /* catch end */".into(),
        Op::DeviceWrite(id) => format!(
            "{{ Chain v = pop(&s); olang_device_write(\"{}\", (uint8_t)(v & 0xFF)); }}",
            escape(id)
        ),
        Op::DeviceRead(id) => format!(
            "push(&s, olang_device_read(\"{}\"));",
            escape(id)
        ),
        Op::DeviceList => "olang_device_list();".into(),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Rust backend
// ─────────────────────────────────────────────────────────────────────────────

fn emit_rust(prog: &OlangProgram) -> Result<String, CompileError> {
    let mut out = String::new();
    let targets = collect_jump_targets(prog);
    let has_jumps = !targets.is_empty();
    let has_try = prog.ops.iter().any(|op| matches!(op, Op::TryBegin(_)));

    out.push_str("// generated by olang compiler\n");
    out.push_str("use olang::molecular::MolecularChain;\n\n");
    out.push_str("extern \"C\" {\n");
    out.push_str("    fn olang_lca(a: u64, b: u64) -> u64;\n");
    out.push_str("    fn olang_load(name: *const u8) -> u64;\n");
    out.push_str("    fn olang_emit(chain: u64);\n");
    out.push_str("    fn olang_edge(a: u64, b: u64, rel: u8);\n");
    out.push_str("    // Device I/O: Olang → HAL → hardware\n");
    out.push_str("    fn olang_device_write(id: *const u8, value: u8) -> i32;\n");
    out.push_str("    fn olang_device_read(id: *const u8) -> u64;\n");
    out.push_str("    fn olang_device_list();\n");
    out.push_str("}\n\n");

    let fn_name = prog.name.replace([' ', '-'], "_");
    out.push_str(&format!("pub fn {}() {{\n", fn_name));
    out.push_str("    let mut stack: Vec<u64> = Vec::new();\n");

    if has_jumps {
        // PC-based state machine for programs with jumps
        out.push_str("    let mut _pc: usize = 0;\n");
        if has_try {
            out.push_str("    let mut _catch_stack: Vec<usize> = Vec::new();\n");
        }
        out.push_str("    loop {\n");
        out.push_str("        match _pc {\n");

        for (i, op) in prog.ops.iter().enumerate() {
            let body = rust_op_jump(op, i, has_try)?;
            out.push_str(&format!("            {} => {{ {} }}\n", i, body));
        }

        let end = prog.ops.len();
        out.push_str(&format!("            _ => break, // pc={} end\n", end));
        out.push_str("        }\n");
        out.push_str("    }\n");
    } else {
        // Linear mode — no jumps, emit directly
        for (i, op) in prog.ops.iter().enumerate() {
            let line = rust_op_linear(op, i)?;
            if !line.is_empty() {
                out.push_str("    ");
                out.push_str(&line);
                out.push('\n');
            }
        }
    }

    out.push_str("}\n");
    Ok(out)
}

/// Rust op for linear mode (no jumps).
fn rust_op_linear(op: &Op, _idx: usize) -> Result<String, CompileError> {
    Ok(match op {
        Op::Push(chain) =>
            format!("stack.push(0x{:016X}_u64);", chain.chain_hash()),
        Op::Load(name) =>
            format!("stack.push(unsafe {{ olang_load(b\"{}\\0\".as_ptr()) }});", escape(name)),
        Op::Lca =>
            "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(unsafe { olang_lca(a, b) }); }".into(),
        Op::Edge(rel) =>
            format!("{{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); unsafe {{ olang_edge(a, b, 0x{:02X}); }} }}", rel),
        Op::Query(rel) =>
            format!("{{ let a = *stack.last().unwrap(); unsafe {{ olang_edge(a, a, 0x{:02X}); }} }}", rel),
        Op::Emit =>
            "{ let c = stack.pop().unwrap(); unsafe { olang_emit(c); } }".into(),
        Op::Dup  => "stack.push(*stack.last().unwrap());".into(),
        Op::Pop  => "stack.pop();".into(),
        Op::Swap => "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(b); stack.push(a); }".into(),
        Op::Halt | Op::Ret => "return;".into(),
        Op::Nop | Op::Dream | Op::Stats => "// nop".into(),
        Op::Loop(n) => format!("for _ in 0..{} {{", n),
        Op::Call(name) => format!("{}();", name.replace(' ', "_")),
        Op::Jmp(_) | Op::Jz(_) => "// unreachable in linear mode".into(),
        Op::Store(name) => format!("// store local: {}", name),
        Op::StoreUpdate(name) => format!("// store update: {}", name),
        Op::LoadLocal(name) => format!("// load local: {}", name),
        Op::PushNum(n) => format!("stack.push(({:.17e}_f64).to_bits());", n),
        Op::Fuse => "// QT2: FUSE — verify chain finite (∞-1)".into(),
        Op::ScopeBegin => "{ // scope begin".into(),
        Op::ScopeEnd => "} // scope end".into(),
        Op::Trace => "eprintln!(\"[TRACE] depth={}\", stack.len());".into(),
        Op::Inspect => "{ let c = *stack.last().unwrap_or(&0); eprintln!(\"[INSPECT] hash=0x{:016X} depth={}\", c, stack.len()); }".into(),
        Op::Assert => "if stack.last().copied().unwrap_or(0) == 0 { eprintln!(\"[ASSERT FAILED]\"); return; }".into(),
        Op::TypeOf => "{ let c = *stack.last().unwrap_or(&0); eprintln!(\"[TYPEOF] 0x{:016X}\", c); }".into(),
        Op::Why => "{ let b = stack.pop().unwrap_or(0); let a = *stack.last().unwrap_or(&0); eprintln!(\"[WHY] 0x{:X} <-> 0x{:X}\", a, b); }".into(),
        Op::Explain => "{ let c = *stack.last().unwrap_or(&0); eprintln!(\"[EXPLAIN] 0x{:016X}\", c); }".into(),
        Op::PushMol(s, r, v, a, t) => format!(
            "stack.push(Molecule::new(0x{:02X},0x{:02X},0x{:02X},0x{:02X},0x{:02X}).into());",
            s, r, v, a, t
        ),
        Op::TryBegin(_) => "// try block begin".into(),
        Op::CatchEnd => "// catch block end".into(),
        Op::DeviceWrite(id) => format!(
            "{{ let v = stack.pop().unwrap_or(0); unsafe {{ olang_device_write(b\"{}\\0\".as_ptr(), (v & 0xFF) as u8); }} }}",
            escape(id)
        ),
        Op::DeviceRead(id) => format!(
            "stack.push(unsafe {{ olang_device_read(b\"{}\\0\".as_ptr()) }});",
            escape(id)
        ),
        Op::DeviceList => "unsafe { olang_device_list(); }".into(),
    })
}

/// Rust op for jump mode (PC-based state machine).
fn rust_op_jump(op: &Op, idx: usize, has_try: bool) -> Result<String, CompileError> {
    let next = idx + 1;
    Ok(match op {
        Op::Push(chain) =>
            format!("stack.push(0x{:016X}_u64); _pc = {};", chain.chain_hash(), next),
        Op::Load(name) =>
            format!("stack.push(unsafe {{ olang_load(b\"{}\\0\".as_ptr()) }}); _pc = {};", escape(name), next),
        Op::Lca =>
            format!("{{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(unsafe {{ olang_lca(a, b) }}); }} _pc = {};", next),
        Op::Edge(rel) =>
            format!("{{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); unsafe {{ olang_edge(a, b, 0x{:02X}); }} }} _pc = {};", rel, next),
        Op::Query(rel) =>
            format!("{{ let a = *stack.last().unwrap(); unsafe {{ olang_edge(a, a, 0x{:02X}); }} }} _pc = {};", rel, next),
        Op::Emit =>
            format!("{{ let c = stack.pop().unwrap(); unsafe {{ olang_emit(c); }} }} _pc = {};", next),
        Op::Dup  => format!("stack.push(*stack.last().unwrap()); _pc = {};", next),
        Op::Pop  => format!("stack.pop(); _pc = {};", next),
        Op::Swap => format!("{{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(b); stack.push(a); }} _pc = {};", next),
        Op::Halt | Op::Ret => "break;".into(),
        Op::Nop  => format!("_pc = {}; // nop", next),
        Op::Dream | Op::Stats => format!("_pc = {}; // system cmd", next),
        Op::Loop(n) => format!("for _ in 0..{} {{ /* loop body follows */ }} _pc = {};", n, next),
        Op::Call(name) => format!("{}(); _pc = {};", name.replace(' ', "_"), next),
        Op::Jmp(t)  => format!("_pc = {};", t),
        Op::Jz(t)   => format!("if stack.pop().unwrap_or(0) == 0 {{ _pc = {}; }} else {{ _pc = {}; }}", t, next),
        Op::Store(name) => format!("/* store {} */ _pc = {};", escape(name), next),
        Op::StoreUpdate(name) => format!("/* store_update {} */ _pc = {};", escape(name), next),
        Op::LoadLocal(name) => format!("/* load {} */ _pc = {};", escape(name), next),
        Op::PushNum(n) => format!("stack.push(({:.17e}_f64).to_bits()); _pc = {};", n, next),
        Op::Fuse => format!("/* QT2: FUSE */ _pc = {};", next),
        Op::ScopeBegin => format!("/* scope begin */ _pc = {};", next),
        Op::ScopeEnd => format!("/* scope end */ _pc = {};", next),
        Op::Trace => format!("eprintln!(\"[TRACE] pc={} depth={{}}\", stack.len()); _pc = {};", idx, next),
        Op::Inspect => format!("{{ let c = *stack.last().unwrap_or(&0); eprintln!(\"[INSPECT] hash=0x{{:016X}} depth={{}}\", c, stack.len()); }} _pc = {};", next),
        Op::Assert => format!("if stack.last().copied().unwrap_or(0) == 0 {{ eprintln!(\"[ASSERT FAILED] pc={}\"); break; }} _pc = {};", idx, next),
        Op::TypeOf => format!("{{ let c = *stack.last().unwrap_or(&0); eprintln!(\"[TYPEOF] 0x{{:016X}}\", c); }} _pc = {};", next),
        Op::Why => format!("{{ let b = stack.pop().unwrap_or(0); let a = *stack.last().unwrap_or(&0); eprintln!(\"[WHY] 0x{{:X}} <-> 0x{{:X}}\", a, b); }} _pc = {};", next),
        Op::Explain => format!("{{ let c = *stack.last().unwrap_or(&0); eprintln!(\"[EXPLAIN] 0x{{:016X}}\", c); }} _pc = {};", next),
        Op::PushMol(s, r, v, a, t) => format!(
            "stack.push(Molecule::new(0x{:02X},0x{:02X},0x{:02X},0x{:02X},0x{:02X}).into()); _pc = {};",
            s, r, v, a, t, next
        ),
        Op::TryBegin(target) => {
            if has_try {
                format!("_catch_stack.push({}); _pc = {};", target, next)
            } else {
                format!("_pc = {};", next)
            }
        }
        Op::CatchEnd => {
            if has_try {
                format!("_catch_stack.pop(); _pc = {};", next)
            } else {
                format!("_pc = {};", next)
            }
        }
        Op::DeviceWrite(id) => format!(
            "{{ let v = stack.pop().unwrap_or(0); unsafe {{ olang_device_write(b\"{}\\0\".as_ptr(), (v & 0xFF) as u8); }} }} _pc = {};",
            escape(id), next
        ),
        Op::DeviceRead(id) => format!(
            "stack.push(unsafe {{ olang_device_read(b\"{}\\0\".as_ptr()) }}); _pc = {};",
            escape(id), next
        ),
        Op::DeviceList => format!("unsafe {{ olang_device_list(); }} _pc = {};", next),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// WASM (WAT text format)
// ─────────────────────────────────────────────────────────────────────────────

fn emit_wat(prog: &OlangProgram) -> Result<String, CompileError> {
    let mut out = String::new();
    let fn_name = prog.name.replace(' ', "_");
    let targets = collect_jump_targets(prog);
    let has_jumps = !targets.is_empty();

    out.push_str(";; generated by olang compiler\n");
    out.push_str("(module\n");

    // Import runtime functions
    out.push_str("  (import \"olang\" \"lca\"   (func $lca   (param i64 i64) (result i64)))\n");
    out.push_str("  (import \"olang\" \"load\"  (func $load  (param i32) (result i64)))\n");
    out.push_str("  (import \"olang\" \"emit\"  (func $emit  (param i64)))\n");
    out.push_str("  (import \"olang\" \"edge\"  (func $edge  (param i64 i64 i32)))\n");
    out.push_str("  (import \"olang\" \"query\" (func $query (param i64 i32)))\n");
    out.push_str("  ;; Device I/O: Olang → HAL → hardware\n");
    out.push_str("  (import \"olang\" \"device_write\" (func $device_write (param i32 i32) (result i32)))\n");
    out.push_str("  (import \"olang\" \"device_read\"  (func $device_read  (param i32) (result i64)))\n");
    out.push_str("  (import \"olang\" \"device_list\"  (func $device_list))\n\n");

    // Memory for string literals
    out.push_str("  (memory 1)\n\n");

    // String table
    let mut strings: Vec<String> = Vec::new();
    let mut string_offset = 256u32;
    let mut data_section = String::new();

    for op in &prog.ops {
        if let Op::Load(name) = op {
            if !strings.iter().any(|s| s.as_str() == name.as_str()) {
                let escaped = escape(name.as_str());
                data_section.push_str(&format!(
                    "  (data (i32.const {}) \"{}\\00\")\n",
                    string_offset, escaped
                ));
                strings.push(name.clone());
                string_offset += name.len() as u32 + 1;
            }
        }
    }
    if !data_section.is_empty() {
        out.push_str(&data_section);
        out.push('\n');
    }

    // Function
    out.push_str(&format!("  (func ${} (export \"{}\")\n", fn_name, fn_name));
    out.push_str("    (local $a i64) (local $b i64)\n");

    if has_jumps {
        // PC-based dispatch loop for programs with jumps
        out.push_str("    (local $pc i32)\n");
        out.push_str("    (local.set $pc (i32.const 0))\n");
        out.push_str("    (block $exit\n");
        out.push_str("      (loop $dispatch\n");

        for (i, op) in prog.ops.iter().enumerate() {
            // Each op: check if pc == i, if so execute
            out.push_str(&format!("        ;; op {}\n", i));
            out.push_str(&format!("        (block $skip_{}\n", i));
            out.push_str(&format!("          (br_if $skip_{} (i32.ne (local.get $pc) (i32.const {})))\n", i, i));
            let mut str_off = 256u32 + strings.iter().take_while(|_| true).map(|s| s.len() as u32 + 1).sum::<u32>();
            let line = wat_op_jump(op, i, &mut str_off, prog.ops.len())?;
            out.push_str(&format!("          {}\n", line));
            out.push_str("        )\n");
        }

        out.push_str("        (br $dispatch)\n");
        out.push_str("      )\n");
        out.push_str("    )\n");
    } else {
        // Linear mode — direct stack mapping
        let mut str_offset = 256u32;
        for (i, op) in prog.ops.iter().enumerate() {
            let line = wat_op_linear(op, i, &mut str_offset)?;
            if !line.is_empty() {
                out.push_str("    ");
                out.push_str(&line);
                out.push('\n');
            }
        }
    }

    out.push_str("  )\n");
    out.push_str(")\n");
    Ok(out)
}

/// WAT op for linear mode (no jumps).
fn wat_op_linear(op: &Op, _idx: usize, str_offset: &mut u32) -> Result<String, CompileError> {
    Ok(match op {
        Op::Push(chain) => format!("i64.const 0x{:016X}", chain.chain_hash()),
        Op::Load(name) => {
            let off = *str_offset;
            *str_offset += name.len() as u32 + 1;
            format!("i32.const {}  call $load", off)
        }
        Op::Lca => "local.set $b  local.set $a  local.get $a  local.get $b  call $lca".into(),
        Op::Edge(rel) => format!(
            "local.set $b  local.set $a  local.get $a  local.get $b  i32.const {}  call $edge",
            rel
        ),
        Op::Query(rel) => format!("local.set $a  local.get $a  i32.const {}  call $query", rel),
        Op::Emit => "call $emit".into(),
        Op::Dup => "local.tee $a  local.get $a".into(),
        Op::Pop => "drop".into(),
        Op::Swap => "local.set $b  local.set $a  local.get $b  local.get $a".into(),
        Op::Halt | Op::Ret => "return".into(),
        Op::Nop | Op::Dream | Op::Stats => ";; nop".into(),
        Op::Loop(n) => format!("block $blk  loop $loop  ;; {} iterations", n),
        Op::Call(name) => format!("call ${}", name.replace(' ', "_")),
        Op::Jmp(_) | Op::Jz(_) => ";; unreachable in linear mode".into(),
        Op::Store(_) => "local.set $local ;; store".into(),
        Op::StoreUpdate(_) => "local.set $local ;; store_update".into(),
        Op::LoadLocal(_) => "local.get $local ;; load_local".into(),
        Op::PushNum(n) => format!("f64.const {:.17e}", n),
        Op::Fuse => ";; QT2: FUSE — verify chain finite".into(),
        Op::ScopeBegin => "block $scope ;; scope begin".into(),
        Op::ScopeEnd => "end ;; scope end".into(),
        Op::Trace => ";; [TRACE] — debug hook (import olang_trace for full support)".into(),
        Op::Inspect => ";; [INSPECT] top of stack — debug hook".into(),
        Op::Assert => ";; [ASSERT] check top non-zero, trap if zero\n    local.get $local\n    i64.eqz\n    (if (then unreachable))".into(),
        Op::TypeOf => ";; [TYPEOF] — debug hook".into(),
        Op::Why => ";; [WHY] — pop second, keep first".into(),
        Op::Explain => ";; [EXPLAIN] — debug hook".into(),
        Op::PushMol(s, r, v, a, t) => format!(
            "i32.const 0x{:02X}{:02X}{:02X}{:02X}{:02X} ;; mol S={} R={} V={} A={} T={}",
            s, r, v, a, t, s, r, v, a, t
        ),
        Op::TryBegin(_) => ";; try block begin".into(),
        Op::CatchEnd => ";; catch block end".into(),
        Op::DeviceWrite(id) => format!(
            "local.set $a  i32.const 256  i64.wrap_i32  i32.const 0  call $device_write  drop  ;; device_write \"{}\"",
            escape(id)
        ),
        Op::DeviceRead(id) => format!(
            "i32.const 256  call $device_read  ;; device_read \"{}\"",
            escape(id)
        ),
        Op::DeviceList => "call $device_list  ;; list devices".into(),
    })
}

/// WAT op for jump mode (PC-based dispatch).
fn wat_op_jump(op: &Op, idx: usize, _str_offset: &mut u32, _total: usize) -> Result<String, CompileError> {
    let next = idx + 1;
    Ok(match op {
        Op::Push(chain) =>
            format!("(i64.const 0x{:016X}) (local.set $pc (i32.const {})) (br $dispatch)", chain.chain_hash(), next),
        Op::Load(name) =>
            format!("(i32.const 256) (call $load) ;; {} (local.set $pc (i32.const {})) (br $dispatch)", escape(name), next),
        Op::Lca =>
            format!("(local.set $b) (local.set $a) (local.get $a) (local.get $b) (call $lca) (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::Edge(rel) =>
            format!("(local.set $b) (local.set $a) (local.get $a) (local.get $b) (i32.const {}) (call $edge) (local.set $pc (i32.const {})) (br $dispatch)", rel, next),
        Op::Query(rel) =>
            format!("(local.set $a) (local.get $a) (i32.const {}) (call $query) (local.set $pc (i32.const {})) (br $dispatch)", rel, next),
        Op::Emit =>
            format!("(call $emit) (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::Dup =>
            format!("(local.tee $a) (local.get $a) (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::Pop =>
            format!("(drop) (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::Swap =>
            format!("(local.set $b) (local.set $a) (local.get $b) (local.get $a) (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::Halt | Op::Ret =>
            "(br $exit)".into(),
        Op::Nop | Op::Dream | Op::Stats =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; nop", next),
        Op::Loop(n) =>
            format!(";; loop {} (local.set $pc (i32.const {})) (br $dispatch)", n, next),
        Op::Call(name) =>
            format!("(call ${}) (local.set $pc (i32.const {})) (br $dispatch)", name.replace(' ', "_"), next),
        Op::Jmp(t)  =>
            format!("(local.set $pc (i32.const {})) (br $dispatch)", t),
        Op::Jz(t)   =>
            format!("(i64.eqz) (if (then (local.set $pc (i32.const {})) (br $dispatch)) (else (local.set $pc (i32.const {})) (br $dispatch)))", t, next),
        Op::Store(_) =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; store", next),
        Op::StoreUpdate(_) =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; store_update", next),
        Op::LoadLocal(_) =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; load_local", next),
        Op::PushNum(n) =>
            format!("(f64.const {:.17e}) (local.set $pc (i32.const {})) (br $dispatch)", n, next),
        Op::Fuse =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; fuse", next),
        Op::ScopeBegin | Op::ScopeEnd =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; scope", next),
        Op::Trace =>
            format!(";; [TRACE] pc={}\n    (local.set $pc (i32.const {})) (br $dispatch)", idx, next),
        Op::Inspect =>
            format!(";; [INSPECT]\n    (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::Assert =>
            format!(";; [ASSERT] trap if zero\n    (local.get $local) (i64.eqz) (if (then (unreachable)))\n    (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::TypeOf | Op::Why | Op::Explain =>
            format!(";; debug primitive\n    (local.set $pc (i32.const {})) (br $dispatch)", next),
        Op::PushMol(s, r, v, a, t) =>
            format!("(i32.const 0x{:02X}{:02X}{:02X}{:02X}{:02X}) (local.set $pc (i32.const {})) (br $dispatch) ;; mol", s, r, v, a, t, next),
        Op::TryBegin(_target) =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; try begin", next),
        Op::CatchEnd =>
            format!("(local.set $pc (i32.const {})) (br $dispatch) ;; catch end", next),
        Op::DeviceWrite(id) =>
            format!("(i32.const 256) (i32.const 0) (call $device_write) (drop) (local.set $pc (i32.const {})) (br $dispatch) ;; device_write \"{}\"", next, escape(id)),
        Op::DeviceRead(id) =>
            format!("(i32.const 256) (call $device_read) (local.set $pc (i32.const {})) (br $dispatch) ;; device_read \"{}\"", next, escape(id)),
        Op::DeviceList =>
            format!("(call $device_list) (local.set $pc (i32.const {})) (br $dispatch) ;; device_list", next),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\0', "\\0")
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::encoder::encode_codepoint;
    use crate::ir::{compile_expr, OlangIrExpr, OlangProgram};

    fn simple_prog() -> OlangProgram {
        compile_expr(&OlangIrExpr::Query("fire".into()))
    }

    fn compose_prog() -> OlangProgram {
        compile_expr(&OlangIrExpr::Compose("fire".into(), "water".into()))
    }

    // ── C backend ─────────────────────────────────────────────────────────────

    #[test]
    fn c_output_compiles_header() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("#include"), "C header");
        assert!(src.contains("void "), "C function");
        assert!(src.contains("Stack"), "Stack type");
    }

    #[test]
    fn c_load_op_emitted() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("olang_load"), "Load extern call");
        assert!(src.contains("fire"), "Name preserved");
    }

    #[test]
    fn c_compose_has_lca() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&compose_prog()).unwrap();
        assert!(src.contains("olang_lca"), "LCA call for compose");
    }

    #[test]
    fn c_output_not_empty() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.len() > 100, "C output đủ dài: {} chars", src.len());
    }

    // ── Rust backend ──────────────────────────────────────────────────────────

    #[test]
    fn rust_output_has_fn() {
        let c = Compiler::new(Target::Rust);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("pub fn"), "Rust function");
        assert!(src.contains("Vec<u64>"), "Stack type");
    }

    #[test]
    fn rust_compose_has_lca() {
        let c = Compiler::new(Target::Rust);
        let src = c.emit(&compose_prog()).unwrap();
        assert!(src.contains("olang_lca"), "Rust LCA call");
    }

    #[test]
    fn rust_unsafe_for_ffi() {
        let c = Compiler::new(Target::Rust);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("unsafe"), "FFI cần unsafe");
    }

    // ── WASM (WAT) backend ────────────────────────────────────────────────────

    #[test]
    fn wat_valid_module() {
        let c = Compiler::new(Target::Wasm);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.starts_with(";; generated"), "WAT header");
        assert!(src.contains("(module"), "module keyword");
        assert!(src.contains("(import"), "imports");
        assert!(src.contains("(func"), "function");
        assert!(src.ends_with(")\n"), "module close");
    }

    #[test]
    fn wat_imports_runtime() {
        let c = Compiler::new(Target::Wasm);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("\"olang\" \"lca\""), "lca import");
        assert!(src.contains("\"olang\" \"load\""), "load import");
        assert!(src.contains("\"olang\" \"emit\""), "emit import");
    }

    #[test]
    fn wat_compose_has_lca_call() {
        let c = Compiler::new(Target::Wasm);
        let src = c.emit(&compose_prog()).unwrap();
        assert!(src.contains("call $lca"), "LCA call trong WAT");
    }

    // ── All targets ───────────────────────────────────────────────────────────

    #[test]
    fn all_targets_succeed() {
        let prog = compose_prog();
        for target in [Target::C, Target::Rust, Target::Wasm] {
            let result = Compiler::new(target).emit(&prog);
            assert!(
                result.is_ok(),
                "{} compilation failed: {:?}",
                target.name(),
                result.err()
            );
            let src = result.unwrap();
            assert!(!src.is_empty(), "{} output rỗng", target.name());
        }
    }

    #[test]
    fn target_file_extensions() {
        assert_eq!(Target::C.file_ext(), "c");
        assert_eq!(Target::Rust.file_ext(), "rs");
        assert_eq!(Target::Wasm.file_ext(), "wat");
    }

    #[test]
    fn all_opcodes_compile_c() {
        // Verify không panic khi gặp bất kỳ opcode nào
        let chain = encode_codepoint(0x1F525);
        let ops_to_test: &[Op] = &[
            Op::Push(chain.clone()),
            Op::Load("test".into()),
            Op::Lca,
            Op::Emit,
            Op::Dup,
            Op::Pop,
            Op::Swap,
            Op::Ret,
            Op::Halt,
            Op::Nop,
        ];
        for op in ops_to_test {
            let result = c_op(op, 0);
            assert!(result.is_ok(), "C op {:?} failed", op);
        }
    }

    #[test]
    fn program_name_in_function() {
        let prog = simple_prog();
        let src = Compiler::new(Target::C).emit(&prog).unwrap();
        // Function name derived from program name
        assert!(src.contains("void "), "Function declaration");
    }

    #[test]
    fn compile_if_else_all_targets() {
        use crate::ir::{compile_expr, OlangIrExpr};
        let expr = OlangIrExpr::IfElse {
            condition: alloc::boxed::Box::new(OlangIrExpr::Query("fire".into())),
            then_branch: alloc::vec![OlangIrExpr::Command("stats".into())],
            else_branch: alloc::vec![OlangIrExpr::Command("dream".into())],
        };
        let prog = compile_expr(&expr);
        for target in [Target::C, Target::Rust, Target::Wasm] {
            let result = Compiler::new(target).emit(&prog);
            assert!(result.is_ok(), "{} if/else failed: {:?}", target.name(), result.err());
        }
    }

    #[test]
    fn compile_loop_all_targets() {
        use crate::ir::{compile_expr, OlangIrExpr};
        let expr = OlangIrExpr::LoopBlock {
            count: 5,
            body: alloc::vec![OlangIrExpr::Command("stats".into())],
        };
        let prog = compile_expr(&expr);
        for target in [Target::C, Target::Rust, Target::Wasm] {
            let result = Compiler::new(target).emit(&prog);
            assert!(result.is_ok(), "{} loop failed: {:?}", target.name(), result.err());
            let src = result.unwrap();
            // C: for loop, Rust: for loop, WAT: loop structure
            assert!(!src.is_empty(), "{} loop output rỗng", target.name());
        }
    }

    #[test]
    fn compile_fn_def_all_targets() {
        use crate::ir::{compile_expr, OlangIrExpr};
        let expr = OlangIrExpr::FnDef {
            name: "boot".into(),
            body: alloc::vec![OlangIrExpr::Command("stats".into())],
        };
        let prog = compile_expr(&expr);
        for target in [Target::C, Target::Rust, Target::Wasm] {
            let result = Compiler::new(target).emit(&prog);
            assert!(result.is_ok(), "{} fn failed: {:?}", target.name(), result.err());
        }
    }

    // ── Jump control flow ────────────────────────────────────────────────────

    #[test]
    fn rust_if_else_has_state_machine() {
        // if/else compiles to Jz/Jmp → should trigger jump mode
        use crate::ir::{compile_expr, OlangIrExpr};
        let expr = OlangIrExpr::IfElse {
            condition: alloc::boxed::Box::new(OlangIrExpr::Query("fire".into())),
            then_branch: alloc::vec![OlangIrExpr::Command("stats".into())],
            else_branch: alloc::vec![OlangIrExpr::Command("dream".into())],
        };
        let prog = compile_expr(&expr);
        let src = Compiler::new(Target::Rust).emit(&prog).unwrap();
        assert!(src.contains("let mut _pc"), "Rust jump mode: PC variable");
        assert!(src.contains("loop {"), "Rust jump mode: dispatch loop");
        assert!(src.contains("match _pc"), "Rust jump mode: match dispatch");
    }

    #[test]
    fn c_if_else_has_labels() {
        use crate::ir::{compile_expr, OlangIrExpr};
        let expr = OlangIrExpr::IfElse {
            condition: alloc::boxed::Box::new(OlangIrExpr::Query("fire".into())),
            then_branch: alloc::vec![OlangIrExpr::Command("stats".into())],
            else_branch: alloc::vec![OlangIrExpr::Command("dream".into())],
        };
        let prog = compile_expr(&expr);
        let src = Compiler::new(Target::C).emit(&prog).unwrap();
        assert!(src.contains("label_"), "C: jump labels present");
        assert!(src.contains("goto label_"), "C: goto for jumps");
    }

    #[test]
    fn wat_if_else_has_dispatch() {
        use crate::ir::{compile_expr, OlangIrExpr};
        let expr = OlangIrExpr::IfElse {
            condition: alloc::boxed::Box::new(OlangIrExpr::Query("fire".into())),
            then_branch: alloc::vec![OlangIrExpr::Command("stats".into())],
            else_branch: alloc::vec![OlangIrExpr::Command("dream".into())],
        };
        let prog = compile_expr(&expr);
        let src = Compiler::new(Target::Wasm).emit(&prog).unwrap();
        assert!(src.contains("$pc"), "WAT: PC local variable");
        assert!(src.contains("$dispatch"), "WAT: dispatch loop");
        assert!(src.contains("br $dispatch"), "WAT: branch to dispatch");
    }

    #[test]
    fn compile_try_catch_all_targets() {
        let mut prog = OlangProgram::new("try_test");
        prog.push_op(Op::TryBegin(3))
            .push_op(Op::Nop)
            .push_op(Op::Jmp(5))
            .push_op(Op::Nop)     // catch
            .push_op(Op::CatchEnd)
            .push_op(Op::Halt);
        for target in [Target::C, Target::Rust, Target::Wasm] {
            let result = Compiler::new(target).emit(&prog);
            assert!(result.is_ok(), "{} try/catch failed: {:?}", target.name(), result.err());
        }
    }

    // ── Device I/O compiler tests ──────────────────────────────────────────

    #[test]
    fn c_device_write_emits_call() {
        let mut prog = OlangProgram::new("dev_test");
        prog.push_op(Op::PushNum(255.0))
            .push_op(Op::DeviceWrite("relay_0".into()))
            .push_op(Op::Halt);
        let src = Compiler::new(Target::C).emit(&prog).unwrap();
        assert!(src.contains("olang_device_write"), "C: device_write call");
        assert!(src.contains("relay_0"), "C: device_id preserved");
    }

    #[test]
    fn c_device_read_emits_call() {
        let mut prog = OlangProgram::new("dev_test");
        prog.push_op(Op::DeviceRead("dht22".into()))
            .push_op(Op::Emit)
            .push_op(Op::Halt);
        let src = Compiler::new(Target::C).emit(&prog).unwrap();
        assert!(src.contains("olang_device_read"), "C: device_read call");
        assert!(src.contains("dht22"), "C: device_id preserved");
    }

    #[test]
    fn c_device_list_emits_call() {
        let mut prog = OlangProgram::new("dev_test");
        prog.push_op(Op::DeviceList)
            .push_op(Op::Halt);
        let src = Compiler::new(Target::C).emit(&prog).unwrap();
        assert!(src.contains("olang_device_list"), "C: device_list call");
    }

    #[test]
    fn rust_device_ops_emit() {
        let mut prog = OlangProgram::new("dev_test");
        prog.push_op(Op::PushNum(128.0))
            .push_op(Op::DeviceWrite("light_0".into()))
            .push_op(Op::DeviceRead("sensor_temp".into()))
            .push_op(Op::DeviceList)
            .push_op(Op::Halt);
        let src = Compiler::new(Target::Rust).emit(&prog).unwrap();
        assert!(src.contains("olang_device_write"), "Rust: device_write");
        assert!(src.contains("olang_device_read"), "Rust: device_read");
        assert!(src.contains("olang_device_list"), "Rust: device_list");
    }

    #[test]
    fn wat_device_imports() {
        let mut prog = OlangProgram::new("dev_test");
        prog.push_op(Op::DeviceList)
            .push_op(Op::Halt);
        let src = Compiler::new(Target::Wasm).emit(&prog).unwrap();
        assert!(src.contains("\"device_write\""), "WAT: device_write import");
        assert!(src.contains("\"device_read\""), "WAT: device_read import");
        assert!(src.contains("\"device_list\""), "WAT: device_list import");
    }

    #[test]
    fn all_targets_device_ops() {
        let mut prog = OlangProgram::new("dev_test");
        prog.push_op(Op::PushNum(1.0))
            .push_op(Op::DeviceWrite("relay".into()))
            .push_op(Op::DeviceRead("sensor".into()))
            .push_op(Op::DeviceList)
            .push_op(Op::Halt);
        for target in [Target::C, Target::Rust, Target::Wasm] {
            let result = Compiler::new(target).emit(&prog);
            assert!(result.is_ok(), "{} device ops failed: {:?}", target.name(), result.err());
        }
    }

    #[test]
    fn rust_try_catch_has_catch_stack() {
        let mut prog = OlangProgram::new("try_test");
        prog.push_op(Op::TryBegin(3))
            .push_op(Op::Nop)
            .push_op(Op::Jmp(5))
            .push_op(Op::Nop)
            .push_op(Op::CatchEnd)
            .push_op(Op::Halt);
        let src = Compiler::new(Target::Rust).emit(&prog).unwrap();
        assert!(src.contains("_catch_stack"), "Rust: catch stack for try/catch");
    }
}
