//! # compiler — Olang IR → target language
//!
//! OlangProgram (IR opcodes) → C / Rust / WASM text.
//!
//! Pipeline:
//!   OlangIrExpr → compile_expr() → OlangProgram (opcodes)
//!   OlangProgram → Compiler::emit(target) → source code string
//!
//! Targets:
//!   C    — universal, FFI, ARM/x86/embedded via gcc/clang
//!   Rust — native, safe
//!   WASM — text format (.wat), browser/node/server
//!
//! Một backend C = ba platform (C→ARM via cross-compile, C→WASM via emscripten).

#![allow(missing_docs)]
extern crate alloc;
use alloc::string::String;
use alloc::vec::Vec;
use alloc::format;

use crate::ir::{Op, OlangProgram};

// ─────────────────────────────────────────────────────────────────────────────
// Target
// ─────────────────────────────────────────────────────────────────────────────

/// Target language.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(missing_docs)]
pub enum Target {
    C,
    Rust,
    Wasm, // WAT text format
}

impl Target {
    pub fn file_ext(self) -> &'static str {
        match self { Self::C => "c", Self::Rust => "rs", Self::Wasm => "wat" }
    }
    pub fn name(self) -> &'static str {
        match self { Self::C => "C", Self::Rust => "Rust", Self::Wasm => "WASM (WAT)" }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// CompileError
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
#[allow(missing_docs)]
pub struct CompileError {
    pub message: String,
    pub op_idx:  usize,
}

// ─────────────────────────────────────────────────────────────────────────────
// Compiler
// ─────────────────────────────────────────────────────────────────────────────

/// Compiler: OlangProgram → source code string.
pub struct Compiler {
    pub target: Target,
}

impl Compiler {
    pub fn new(target: Target) -> Self { Self { target } }

    /// Compile OlangProgram → source code.
    pub fn emit(&self, prog: &OlangProgram) -> Result<String, CompileError> {
        match self.target {
            Target::C    => emit_c(prog),
            Target::Rust => emit_rust(prog),
            Target::Wasm => emit_wat(prog),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// C backend
// ─────────────────────────────────────────────────────────────────────────────

fn emit_c(prog: &OlangProgram) -> Result<String, CompileError> {
    let mut out = String::new();

    // Header
    out.push_str("/* generated by olang compiler */\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <string.h>\n\n");

    // Runtime types
    out.push_str("typedef uint64_t Chain;\n");
    out.push_str("typedef struct { Chain data[32]; int top; } Stack;\n\n");

    // Runtime helpers
    out.push_str("static void push(Stack *s, Chain v) { s->data[s->top++] = v; }\n");
    out.push_str("static Chain pop(Stack *s) { return s->data[--s->top]; }\n");
    out.push_str("static Chain peek(Stack *s) { return s->data[s->top-1]; }\n");
    out.push_str("/* lca: LCA of two molecular chains */\n");
    out.push_str("extern Chain olang_lca(Chain a, Chain b);\n");
    out.push_str("extern Chain olang_load(const char *name);\n");
    out.push_str("extern void  olang_emit(Chain c);\n");
    out.push_str("extern void  olang_edge(Chain a, Chain b, uint8_t rel);\n");
    out.push_str("extern void  olang_query(Chain a, uint8_t rel);\n\n");

    // Function body
    out.push_str(&format!("void {}(void) {{\n", prog.name.replace(' ', "_")));
    out.push_str("  Stack s = {.top = 0};\n");

    for (i, op) in prog.ops.iter().enumerate() {
        let line = c_op(op, i)?;
        if !line.is_empty() {
            out.push_str("  ");
            out.push_str(&line);
            out.push('\n');
        }
    }

    out.push_str("}\n");
    Ok(out)
}

fn c_op(op: &Op, _idx: usize) -> Result<String, CompileError> {
    Ok(match op {
        Op::Push(chain) =>
            format!("push(&s, 0x{:016X}ULL); /* chain */", chain.chain_hash()),
        Op::Load(name) =>
            format!("push(&s, olang_load(\"{}\"));", escape(name)),
        Op::Lca =>
            "{ Chain b = pop(&s), a = pop(&s); push(&s, olang_lca(a, b)); }".into(),
        Op::Edge(rel) =>
            format!("{{ Chain b = pop(&s), a = pop(&s); olang_edge(a, b, 0x{:02X}); }}", rel),
        Op::Query(rel) =>
            format!("{{ Chain a = pop(&s); olang_query(a, 0x{:02X}); }}", rel),
        Op::Emit =>
            "olang_emit(pop(&s));".into(),
        Op::Dup =>
            "push(&s, peek(&s));".into(),
        Op::Pop =>
            "pop(&s);".into(),
        Op::Swap =>
            "{ Chain b = pop(&s), a = pop(&s); push(&s, b); push(&s, a); }".into(),
        Op::Jmp(target) =>
            format!("goto label_{};", target),
        Op::Jz(target) =>
            format!("if (pop(&s) == 0) goto label_{};", target),
        Op::Loop(n) =>
            format!("for (int _i=0; _i<{}; _i++) {{", n),
        Op::Call(name) =>
            format!("{}();", name.replace(' ', "_")),
        Op::Ret  => "return;".into(),
        Op::Halt => "return;".into(),
        Op::Dream => "/* dream */".into(),
        Op::Stats => "/* stats */".into(),
        Op::Nop   => "".into(),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Rust backend
// ─────────────────────────────────────────────────────────────────────────────

fn emit_rust(prog: &OlangProgram) -> Result<String, CompileError> {
    let mut out = String::new();

    out.push_str("// generated by olang compiler\n");
    out.push_str("use olang::molecular::MolecularChain;\n\n");
    out.push_str("extern \"C\" {\n");
    out.push_str("    fn olang_lca(a: u64, b: u64) -> u64;\n");
    out.push_str("    fn olang_load(name: *const u8) -> u64;\n");
    out.push_str("    fn olang_emit(chain: u64);\n");
    out.push_str("    fn olang_edge(a: u64, b: u64, rel: u8);\n");
    out.push_str("}\n\n");

    let fn_name = prog.name.replace(' ', "_").replace('-', "_");
    out.push_str(&format!("pub fn {}() {{\n", fn_name));
    out.push_str("    let mut stack: Vec<u64> = Vec::new();\n");

    for (i, op) in prog.ops.iter().enumerate() {
        let line = rust_op(op, i)?;
        if !line.is_empty() {
            out.push_str("    ");
            out.push_str(&line);
            out.push('\n');
        }
    }

    out.push_str("}\n");
    Ok(out)
}

fn rust_op(op: &Op, _idx: usize) -> Result<String, CompileError> {
    Ok(match op {
        Op::Push(chain) =>
            format!("stack.push(0x{:016X}_u64);", chain.chain_hash()),
        Op::Load(name) =>
            format!("stack.push(unsafe {{ olang_load(b\"{}\\0\".as_ptr()) }});", escape(name)),
        Op::Lca =>
            "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(unsafe { olang_lca(a, b) }); }".into(),
        Op::Edge(rel) =>
            format!("{{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); unsafe {{ olang_edge(a, b, 0x{:02X}); }} }}", rel),
        Op::Query(rel) =>
            format!("{{ let a = *stack.last().unwrap(); unsafe {{ olang_edge(a, a, 0x{:02X}); }} }}", rel),
        Op::Emit =>
            "{ let c = stack.pop().unwrap(); unsafe { olang_emit(c); } }".into(),
        Op::Dup  => "stack.push(*stack.last().unwrap());".into(),
        Op::Pop  => "stack.pop();".into(),
        Op::Swap => "{ let b = stack.pop().unwrap(); let a = stack.pop().unwrap(); stack.push(b); stack.push(a); }".into(),
        Op::Halt | Op::Ret => "return;".into(),
        Op::Nop | Op::Dream | Op::Stats => "// nop".into(),
        Op::Loop(n) => format!("for _ in 0..{} {{", n),
        Op::Call(name) => format!("{}();", name.replace(' ', "_")),
        Op::Jmp(t) => format!("// jmp {}", t),
        Op::Jz(t)  => format!("// jz {} (runtime check needed)", t),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// WASM (WAT text format)
// ─────────────────────────────────────────────────────────────────────────────

fn emit_wat(prog: &OlangProgram) -> Result<String, CompileError> {
    let mut out = String::new();
    let fn_name = prog.name.replace(' ', "_");

    out.push_str(";; generated by olang compiler\n");
    out.push_str("(module\n");

    // Import runtime functions
    out.push_str("  (import \"olang\" \"lca\"   (func $lca   (param i64 i64) (result i64)))\n");
    out.push_str("  (import \"olang\" \"load\"  (func $load  (param i32) (result i64)))\n");
    out.push_str("  (import \"olang\" \"emit\"  (func $emit  (param i64)))\n");
    out.push_str("  (import \"olang\" \"edge\"  (func $edge  (param i64 i64 i32)))\n");
    out.push_str("  (import \"olang\" \"query\" (func $query (param i64 i32)))\n\n");

    // Memory for string literals
    out.push_str("  (memory 1)\n\n");

    // String table
    let mut strings: Vec<String> = Vec::new();
    let mut string_offset = 256u32; // start after reserved area
    let mut data_section  = String::new();

    // Pre-scan for Load ops to build string table
    for op in &prog.ops {
        if let Op::Load(name) = op {
            if !strings.iter().any(|s| s.as_str() == name.as_str()) {
                let escaped = escape(name.as_str());
                data_section.push_str(&format!(
                    "  (data (i32.const {}) \"{}\\00\")\n",
                    string_offset, escaped
                ));
                strings.push(name.clone());
                string_offset += name.len() as u32 + 1;
            }
        }
    }
    if !data_section.is_empty() {
        out.push_str(&data_section);
        out.push('\n');
    }

    // Function
    out.push_str(&format!("  (func ${} (export \"{}\")\n", fn_name, fn_name));
    out.push_str("    (local $a i64) (local $b i64)\n");

    // WAT uses a stack machine — direct mapping to Olang opcodes
    let mut str_offset = 256u32;
    for (i, op) in prog.ops.iter().enumerate() {
        let line = wat_op(op, i, &mut str_offset)?;
        if !line.is_empty() {
            out.push_str("    ");
            out.push_str(&line);
            out.push('\n');
        }
    }

    out.push_str("  )\n");
    out.push_str(")\n");
    Ok(out)
}

fn wat_op(op: &Op, _idx: usize, str_offset: &mut u32) -> Result<String, CompileError> {
    Ok(match op {
        Op::Push(chain) =>
            format!("i64.const 0x{:016X}", chain.chain_hash()),
        Op::Load(name) => {
            let off = *str_offset;
            *str_offset += name.len() as u32 + 1;
            format!("i32.const {}  call $load", off)
        }
        Op::Lca =>
            "local.set $b  local.set $a  local.get $a  local.get $b  call $lca".into(),
        Op::Edge(rel) =>
            format!("local.set $b  local.set $a  local.get $a  local.get $b  i32.const {}  call $edge", rel),
        Op::Query(rel) =>
            format!("local.set $a  local.get $a  i32.const {}  call $query", rel),
        Op::Emit =>
            "call $emit".into(),
        Op::Dup  => "local.tee $a  local.get $a".into(),
        Op::Pop  => "drop".into(),
        Op::Swap => "local.set $b  local.set $a  local.get $b  local.get $a".into(),
        Op::Halt | Op::Ret  => "return".into(),
        Op::Nop | Op::Dream | Op::Stats => ";; nop".into(),
        Op::Loop(n) => format!("block $blk  loop $loop  ;; {} iterations", n),
        Op::Call(name) => format!("call ${}", name.replace(' ', "_")),
        Op::Jmp(t)  => format!(";; jmp {} (label needed)", t),
        Op::Jz(t)   => format!("i64.eqz  br_if {};; jz", t),
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('\0', "\\0")
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{OlangProgram, OlangIrExpr, compile_expr};
    use crate::encoder::encode_codepoint;

    fn simple_prog() -> OlangProgram {
        compile_expr(&OlangIrExpr::Query("fire".into()))
    }

    fn compose_prog() -> OlangProgram {
        compile_expr(&OlangIrExpr::Compose("fire".into(), "water".into()))
    }

    // ── C backend ─────────────────────────────────────────────────────────────

    #[test]
    fn c_output_compiles_header() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("#include"), "C header");
        assert!(src.contains("void "),    "C function");
        assert!(src.contains("Stack"),    "Stack type");
    }

    #[test]
    fn c_load_op_emitted() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("olang_load"), "Load extern call");
        assert!(src.contains("fire"),       "Name preserved");
    }

    #[test]
    fn c_compose_has_lca() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&compose_prog()).unwrap();
        assert!(src.contains("olang_lca"), "LCA call for compose");
    }

    #[test]
    fn c_output_not_empty() {
        let c = Compiler::new(Target::C);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.len() > 100, "C output đủ dài: {} chars", src.len());
    }

    // ── Rust backend ──────────────────────────────────────────────────────────

    #[test]
    fn rust_output_has_fn() {
        let c = Compiler::new(Target::Rust);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("pub fn"), "Rust function");
        assert!(src.contains("Vec<u64>"), "Stack type");
    }

    #[test]
    fn rust_compose_has_lca() {
        let c = Compiler::new(Target::Rust);
        let src = c.emit(&compose_prog()).unwrap();
        assert!(src.contains("olang_lca"), "Rust LCA call");
    }

    #[test]
    fn rust_unsafe_for_ffi() {
        let c = Compiler::new(Target::Rust);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("unsafe"), "FFI cần unsafe");
    }

    // ── WASM (WAT) backend ────────────────────────────────────────────────────

    #[test]
    fn wat_valid_module() {
        let c = Compiler::new(Target::Wasm);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.starts_with(";; generated"), "WAT header");
        assert!(src.contains("(module"),   "module keyword");
        assert!(src.contains("(import"),   "imports");
        assert!(src.contains("(func"),     "function");
        assert!(src.ends_with(")\n"),      "module close");
    }

    #[test]
    fn wat_imports_runtime() {
        let c = Compiler::new(Target::Wasm);
        let src = c.emit(&simple_prog()).unwrap();
        assert!(src.contains("\"olang\" \"lca\""),  "lca import");
        assert!(src.contains("\"olang\" \"load\""), "load import");
        assert!(src.contains("\"olang\" \"emit\""), "emit import");
    }

    #[test]
    fn wat_compose_has_lca_call() {
        let c = Compiler::new(Target::Wasm);
        let src = c.emit(&compose_prog()).unwrap();
        assert!(src.contains("call $lca"), "LCA call trong WAT");
    }

    // ── All targets ───────────────────────────────────────────────────────────

    #[test]
    fn all_targets_succeed() {
        let prog = compose_prog();
        for target in [Target::C, Target::Rust, Target::Wasm] {
            let result = Compiler::new(target).emit(&prog);
            assert!(result.is_ok(), "{} compilation failed: {:?}", target.name(), result.err());
            let src = result.unwrap();
            assert!(!src.is_empty(), "{} output rỗng", target.name());
        }
    }

    #[test]
    fn target_file_extensions() {
        assert_eq!(Target::C.file_ext(),    "c");
        assert_eq!(Target::Rust.file_ext(), "rs");
        assert_eq!(Target::Wasm.file_ext(), "wat");
    }

    #[test]
    fn all_opcodes_compile_c() {
        // Verify không panic khi gặp bất kỳ opcode nào
        let chain = encode_codepoint(0x1F525);
        let ops_to_test: &[Op] = &[
            Op::Push(chain.clone()),
            Op::Load("test".into()),
            Op::Lca,
            Op::Emit,
            Op::Dup, Op::Pop, Op::Swap,
            Op::Ret, Op::Halt, Op::Nop,
        ];
        for op in ops_to_test {
            let result = c_op(op, 0);
            assert!(result.is_ok(), "C op {:?} failed", op);
        }
    }

    #[test]
    fn program_name_in_function() {
        let prog = simple_prog();
        let src  = Compiler::new(Target::C).emit(&prog).unwrap();
        // Function name derived from program name
        assert!(src.contains("void "), "Function declaration");
    }
}
